// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package twingate

import (
	"context"
	"reflect"

	"github.com/Twingate/pulumi-twingate/sdk/v4/go/twingate/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// X509 Certificate Authorities allow Twingate to verify certificates presented by resources during TLS connections.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/Twingate/pulumi-twingate/sdk/v4/go/twingate"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := twingate.LookupTwingateX509CertificateAuthority(ctx, &twingate.LookupTwingateX509CertificateAuthorityArgs{
//				Id: "<your x509 certificate authority's id>",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupTwingateX509CertificateAuthority(ctx *pulumi.Context, args *LookupTwingateX509CertificateAuthorityArgs, opts ...pulumi.InvokeOption) (*LookupTwingateX509CertificateAuthorityResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupTwingateX509CertificateAuthorityResult
	err := ctx.Invoke("twingate:index/getTwingateX509CertificateAuthority:getTwingateX509CertificateAuthority", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTwingateX509CertificateAuthority.
type LookupTwingateX509CertificateAuthorityArgs struct {
	// The ID of the X509 Certificate Authority.
	Id string `pulumi:"id"`
}

// A collection of values returned by getTwingateX509CertificateAuthority.
type LookupTwingateX509CertificateAuthorityResult struct {
	// The SHA-256 fingerprint of the X509 certificate.
	Fingerprint string `pulumi:"fingerprint"`
	// The ID of the X509 Certificate Authority.
	Id string `pulumi:"id"`
	// The name of the X509 Certificate Authority.
	Name string `pulumi:"name"`
}

func LookupTwingateX509CertificateAuthorityOutput(ctx *pulumi.Context, args LookupTwingateX509CertificateAuthorityOutputArgs, opts ...pulumi.InvokeOption) LookupTwingateX509CertificateAuthorityResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupTwingateX509CertificateAuthorityResultOutput, error) {
			args := v.(LookupTwingateX509CertificateAuthorityArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("twingate:index/getTwingateX509CertificateAuthority:getTwingateX509CertificateAuthority", args, LookupTwingateX509CertificateAuthorityResultOutput{}, options).(LookupTwingateX509CertificateAuthorityResultOutput), nil
		}).(LookupTwingateX509CertificateAuthorityResultOutput)
}

// A collection of arguments for invoking getTwingateX509CertificateAuthority.
type LookupTwingateX509CertificateAuthorityOutputArgs struct {
	// The ID of the X509 Certificate Authority.
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupTwingateX509CertificateAuthorityOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTwingateX509CertificateAuthorityArgs)(nil)).Elem()
}

// A collection of values returned by getTwingateX509CertificateAuthority.
type LookupTwingateX509CertificateAuthorityResultOutput struct{ *pulumi.OutputState }

func (LookupTwingateX509CertificateAuthorityResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTwingateX509CertificateAuthorityResult)(nil)).Elem()
}

func (o LookupTwingateX509CertificateAuthorityResultOutput) ToLookupTwingateX509CertificateAuthorityResultOutput() LookupTwingateX509CertificateAuthorityResultOutput {
	return o
}

func (o LookupTwingateX509CertificateAuthorityResultOutput) ToLookupTwingateX509CertificateAuthorityResultOutputWithContext(ctx context.Context) LookupTwingateX509CertificateAuthorityResultOutput {
	return o
}

// The SHA-256 fingerprint of the X509 certificate.
func (o LookupTwingateX509CertificateAuthorityResultOutput) Fingerprint() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTwingateX509CertificateAuthorityResult) string { return v.Fingerprint }).(pulumi.StringOutput)
}

// The ID of the X509 Certificate Authority.
func (o LookupTwingateX509CertificateAuthorityResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTwingateX509CertificateAuthorityResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the X509 Certificate Authority.
func (o LookupTwingateX509CertificateAuthorityResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTwingateX509CertificateAuthorityResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupTwingateX509CertificateAuthorityResultOutput{})
}
