// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package twingate

import (
	"context"
	"reflect"

	"errors"
	"github.com/Twingate/pulumi-twingate/sdk/v4/go/twingate/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// SSH Certificate Authorities allow Twingate to sign SSH certificates for authenticating users to resources.
type TwingateSSHCertificateAuthority struct {
	pulumi.CustomResourceState

	// The fingerprint of the SSH public key.
	Fingerprint pulumi.StringOutput `pulumi:"fingerprint"`
	// The name of the SSH Certificate Authority.
	Name pulumi.StringOutput `pulumi:"name"`
	// The SSH public key in OpenSSH authorizedKeys format.
	PublicKey pulumi.StringOutput `pulumi:"publicKey"`
}

// NewTwingateSSHCertificateAuthority registers a new resource with the given unique name, arguments, and options.
func NewTwingateSSHCertificateAuthority(ctx *pulumi.Context,
	name string, args *TwingateSSHCertificateAuthorityArgs, opts ...pulumi.ResourceOption) (*TwingateSSHCertificateAuthority, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PublicKey == nil {
		return nil, errors.New("invalid value for required argument 'PublicKey'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource TwingateSSHCertificateAuthority
	err := ctx.RegisterResource("twingate:index/twingateSSHCertificateAuthority:TwingateSSHCertificateAuthority", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTwingateSSHCertificateAuthority gets an existing TwingateSSHCertificateAuthority resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTwingateSSHCertificateAuthority(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TwingateSSHCertificateAuthorityState, opts ...pulumi.ResourceOption) (*TwingateSSHCertificateAuthority, error) {
	var resource TwingateSSHCertificateAuthority
	err := ctx.ReadResource("twingate:index/twingateSSHCertificateAuthority:TwingateSSHCertificateAuthority", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TwingateSSHCertificateAuthority resources.
type twingateSSHCertificateAuthorityState struct {
	// The fingerprint of the SSH public key.
	Fingerprint *string `pulumi:"fingerprint"`
	// The name of the SSH Certificate Authority.
	Name *string `pulumi:"name"`
	// The SSH public key in OpenSSH authorizedKeys format.
	PublicKey *string `pulumi:"publicKey"`
}

type TwingateSSHCertificateAuthorityState struct {
	// The fingerprint of the SSH public key.
	Fingerprint pulumi.StringPtrInput
	// The name of the SSH Certificate Authority.
	Name pulumi.StringPtrInput
	// The SSH public key in OpenSSH authorizedKeys format.
	PublicKey pulumi.StringPtrInput
}

func (TwingateSSHCertificateAuthorityState) ElementType() reflect.Type {
	return reflect.TypeOf((*twingateSSHCertificateAuthorityState)(nil)).Elem()
}

type twingateSSHCertificateAuthorityArgs struct {
	// The name of the SSH Certificate Authority.
	Name *string `pulumi:"name"`
	// The SSH public key in OpenSSH authorizedKeys format.
	PublicKey string `pulumi:"publicKey"`
}

// The set of arguments for constructing a TwingateSSHCertificateAuthority resource.
type TwingateSSHCertificateAuthorityArgs struct {
	// The name of the SSH Certificate Authority.
	Name pulumi.StringPtrInput
	// The SSH public key in OpenSSH authorizedKeys format.
	PublicKey pulumi.StringInput
}

func (TwingateSSHCertificateAuthorityArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*twingateSSHCertificateAuthorityArgs)(nil)).Elem()
}

type TwingateSSHCertificateAuthorityInput interface {
	pulumi.Input

	ToTwingateSSHCertificateAuthorityOutput() TwingateSSHCertificateAuthorityOutput
	ToTwingateSSHCertificateAuthorityOutputWithContext(ctx context.Context) TwingateSSHCertificateAuthorityOutput
}

func (*TwingateSSHCertificateAuthority) ElementType() reflect.Type {
	return reflect.TypeOf((**TwingateSSHCertificateAuthority)(nil)).Elem()
}

func (i *TwingateSSHCertificateAuthority) ToTwingateSSHCertificateAuthorityOutput() TwingateSSHCertificateAuthorityOutput {
	return i.ToTwingateSSHCertificateAuthorityOutputWithContext(context.Background())
}

func (i *TwingateSSHCertificateAuthority) ToTwingateSSHCertificateAuthorityOutputWithContext(ctx context.Context) TwingateSSHCertificateAuthorityOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TwingateSSHCertificateAuthorityOutput)
}

// TwingateSSHCertificateAuthorityArrayInput is an input type that accepts TwingateSSHCertificateAuthorityArray and TwingateSSHCertificateAuthorityArrayOutput values.
// You can construct a concrete instance of `TwingateSSHCertificateAuthorityArrayInput` via:
//
//	TwingateSSHCertificateAuthorityArray{ TwingateSSHCertificateAuthorityArgs{...} }
type TwingateSSHCertificateAuthorityArrayInput interface {
	pulumi.Input

	ToTwingateSSHCertificateAuthorityArrayOutput() TwingateSSHCertificateAuthorityArrayOutput
	ToTwingateSSHCertificateAuthorityArrayOutputWithContext(context.Context) TwingateSSHCertificateAuthorityArrayOutput
}

type TwingateSSHCertificateAuthorityArray []TwingateSSHCertificateAuthorityInput

func (TwingateSSHCertificateAuthorityArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TwingateSSHCertificateAuthority)(nil)).Elem()
}

func (i TwingateSSHCertificateAuthorityArray) ToTwingateSSHCertificateAuthorityArrayOutput() TwingateSSHCertificateAuthorityArrayOutput {
	return i.ToTwingateSSHCertificateAuthorityArrayOutputWithContext(context.Background())
}

func (i TwingateSSHCertificateAuthorityArray) ToTwingateSSHCertificateAuthorityArrayOutputWithContext(ctx context.Context) TwingateSSHCertificateAuthorityArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TwingateSSHCertificateAuthorityArrayOutput)
}

// TwingateSSHCertificateAuthorityMapInput is an input type that accepts TwingateSSHCertificateAuthorityMap and TwingateSSHCertificateAuthorityMapOutput values.
// You can construct a concrete instance of `TwingateSSHCertificateAuthorityMapInput` via:
//
//	TwingateSSHCertificateAuthorityMap{ "key": TwingateSSHCertificateAuthorityArgs{...} }
type TwingateSSHCertificateAuthorityMapInput interface {
	pulumi.Input

	ToTwingateSSHCertificateAuthorityMapOutput() TwingateSSHCertificateAuthorityMapOutput
	ToTwingateSSHCertificateAuthorityMapOutputWithContext(context.Context) TwingateSSHCertificateAuthorityMapOutput
}

type TwingateSSHCertificateAuthorityMap map[string]TwingateSSHCertificateAuthorityInput

func (TwingateSSHCertificateAuthorityMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TwingateSSHCertificateAuthority)(nil)).Elem()
}

func (i TwingateSSHCertificateAuthorityMap) ToTwingateSSHCertificateAuthorityMapOutput() TwingateSSHCertificateAuthorityMapOutput {
	return i.ToTwingateSSHCertificateAuthorityMapOutputWithContext(context.Background())
}

func (i TwingateSSHCertificateAuthorityMap) ToTwingateSSHCertificateAuthorityMapOutputWithContext(ctx context.Context) TwingateSSHCertificateAuthorityMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TwingateSSHCertificateAuthorityMapOutput)
}

type TwingateSSHCertificateAuthorityOutput struct{ *pulumi.OutputState }

func (TwingateSSHCertificateAuthorityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TwingateSSHCertificateAuthority)(nil)).Elem()
}

func (o TwingateSSHCertificateAuthorityOutput) ToTwingateSSHCertificateAuthorityOutput() TwingateSSHCertificateAuthorityOutput {
	return o
}

func (o TwingateSSHCertificateAuthorityOutput) ToTwingateSSHCertificateAuthorityOutputWithContext(ctx context.Context) TwingateSSHCertificateAuthorityOutput {
	return o
}

// The fingerprint of the SSH public key.
func (o TwingateSSHCertificateAuthorityOutput) Fingerprint() pulumi.StringOutput {
	return o.ApplyT(func(v *TwingateSSHCertificateAuthority) pulumi.StringOutput { return v.Fingerprint }).(pulumi.StringOutput)
}

// The name of the SSH Certificate Authority.
func (o TwingateSSHCertificateAuthorityOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *TwingateSSHCertificateAuthority) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The SSH public key in OpenSSH authorizedKeys format.
func (o TwingateSSHCertificateAuthorityOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *TwingateSSHCertificateAuthority) pulumi.StringOutput { return v.PublicKey }).(pulumi.StringOutput)
}

type TwingateSSHCertificateAuthorityArrayOutput struct{ *pulumi.OutputState }

func (TwingateSSHCertificateAuthorityArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TwingateSSHCertificateAuthority)(nil)).Elem()
}

func (o TwingateSSHCertificateAuthorityArrayOutput) ToTwingateSSHCertificateAuthorityArrayOutput() TwingateSSHCertificateAuthorityArrayOutput {
	return o
}

func (o TwingateSSHCertificateAuthorityArrayOutput) ToTwingateSSHCertificateAuthorityArrayOutputWithContext(ctx context.Context) TwingateSSHCertificateAuthorityArrayOutput {
	return o
}

func (o TwingateSSHCertificateAuthorityArrayOutput) Index(i pulumi.IntInput) TwingateSSHCertificateAuthorityOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *TwingateSSHCertificateAuthority {
		return vs[0].([]*TwingateSSHCertificateAuthority)[vs[1].(int)]
	}).(TwingateSSHCertificateAuthorityOutput)
}

type TwingateSSHCertificateAuthorityMapOutput struct{ *pulumi.OutputState }

func (TwingateSSHCertificateAuthorityMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TwingateSSHCertificateAuthority)(nil)).Elem()
}

func (o TwingateSSHCertificateAuthorityMapOutput) ToTwingateSSHCertificateAuthorityMapOutput() TwingateSSHCertificateAuthorityMapOutput {
	return o
}

func (o TwingateSSHCertificateAuthorityMapOutput) ToTwingateSSHCertificateAuthorityMapOutputWithContext(ctx context.Context) TwingateSSHCertificateAuthorityMapOutput {
	return o
}

func (o TwingateSSHCertificateAuthorityMapOutput) MapIndex(k pulumi.StringInput) TwingateSSHCertificateAuthorityOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *TwingateSSHCertificateAuthority {
		return vs[0].(map[string]*TwingateSSHCertificateAuthority)[vs[1].(string)]
	}).(TwingateSSHCertificateAuthorityOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TwingateSSHCertificateAuthorityInput)(nil)).Elem(), &TwingateSSHCertificateAuthority{})
	pulumi.RegisterInputType(reflect.TypeOf((*TwingateSSHCertificateAuthorityArrayInput)(nil)).Elem(), TwingateSSHCertificateAuthorityArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TwingateSSHCertificateAuthorityMapInput)(nil)).Elem(), TwingateSSHCertificateAuthorityMap{})
	pulumi.RegisterOutputType(TwingateSSHCertificateAuthorityOutput{})
	pulumi.RegisterOutputType(TwingateSSHCertificateAuthorityArrayOutput{})
	pulumi.RegisterOutputType(TwingateSSHCertificateAuthorityMapOutput{})
}
