// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package twingate

import (
	"context"
	"reflect"

	"errors"
	"github.com/Twingate/pulumi-twingate/sdk/v4/go/twingate/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Gateways are the Twingate components that route traffic to remote networks.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/Twingate/pulumi-twingate/sdk/v4/go/twingate"
//	"github.com/pulumi/pulumi-std/sdk/v2/go/std"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			gcp, err := twingate.NewTwingateRemoteNetwork(ctx, "gcp", &twingate.TwingateRemoteNetworkArgs{
//				Name: pulumi.String("GCP Network"),
//			})
//			if err != nil {
//				return err
//			}
//			invokeFile, err := std.File(ctx, &std.FileArgs{
//				Input: "ca.pem",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			tls, err := twingate.NewTwingateX509CertificateAuthority(ctx, "tls", &twingate.TwingateX509CertificateAuthorityArgs{
//				Name:        pulumi.String("My TLS CA"),
//				Certificate: pulumi.String(invokeFile.Result),
//			})
//			if err != nil {
//				return err
//			}
//			invokeTrimspace1, err := std.Trimspace(ctx, &std.TrimspaceArgs{
//				Input: std.File(ctx, &std.FileArgs{
//					Input: "~/.ssh/id_ed25519.pub",
//				}, nil).Result,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ssh, err := twingate.NewTwingateSSHCertificateAuthority(ctx, "ssh", &twingate.TwingateSSHCertificateAuthorityArgs{
//				Name:      pulumi.String("My SSH CA"),
//				PublicKey: pulumi.String(invokeTrimspace1.Result),
//			})
//			if err != nil {
//				return err
//			}
//			// Gateway with both X.509 and SSH CAs
//			_, err = twingate.NewTwingateGateway(ctx, "main", &twingate.TwingateGatewayArgs{
//				RemoteNetworkId: gcp.ID(),
//				Address:         pulumi.String("10.0.0.1:8443"),
//				X509CaId:        tls.ID(),
//				SshCaId:         ssh.ID(),
//			})
//			if err != nil {
//				return err
//			}
//			// Gateway with only X.509 CA (ssh_ca_id is optional)
//			_, err = twingate.NewTwingateGateway(ctx, "minimal", &twingate.TwingateGatewayArgs{
//				RemoteNetworkId: gcp.ID(),
//				Address:         pulumi.String("10.0.0.2:9001"),
//				X509CaId:        tls.ID(),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type TwingateGateway struct {
	pulumi.CustomResourceState

	// The address of the Gateway.
	Address pulumi.StringOutput `pulumi:"address"`
	// The ID of the Remote Network the Gateway belongs to.
	RemoteNetworkId pulumi.StringOutput `pulumi:"remoteNetworkId"`
	// The ID of the SSH Certificate Authority used for SSH access.
	SshCaId pulumi.StringPtrOutput `pulumi:"sshCaId"`
	// The ID of the X.509 Certificate Authority used for TLS.
	X509CaId pulumi.StringOutput `pulumi:"x509CaId"`
}

// NewTwingateGateway registers a new resource with the given unique name, arguments, and options.
func NewTwingateGateway(ctx *pulumi.Context,
	name string, args *TwingateGatewayArgs, opts ...pulumi.ResourceOption) (*TwingateGateway, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Address == nil {
		return nil, errors.New("invalid value for required argument 'Address'")
	}
	if args.RemoteNetworkId == nil {
		return nil, errors.New("invalid value for required argument 'RemoteNetworkId'")
	}
	if args.X509CaId == nil {
		return nil, errors.New("invalid value for required argument 'X509CaId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource TwingateGateway
	err := ctx.RegisterResource("twingate:index/twingateGateway:TwingateGateway", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTwingateGateway gets an existing TwingateGateway resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTwingateGateway(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TwingateGatewayState, opts ...pulumi.ResourceOption) (*TwingateGateway, error) {
	var resource TwingateGateway
	err := ctx.ReadResource("twingate:index/twingateGateway:TwingateGateway", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TwingateGateway resources.
type twingateGatewayState struct {
	// The address of the Gateway.
	Address *string `pulumi:"address"`
	// The ID of the Remote Network the Gateway belongs to.
	RemoteNetworkId *string `pulumi:"remoteNetworkId"`
	// The ID of the SSH Certificate Authority used for SSH access.
	SshCaId *string `pulumi:"sshCaId"`
	// The ID of the X.509 Certificate Authority used for TLS.
	X509CaId *string `pulumi:"x509CaId"`
}

type TwingateGatewayState struct {
	// The address of the Gateway.
	Address pulumi.StringPtrInput
	// The ID of the Remote Network the Gateway belongs to.
	RemoteNetworkId pulumi.StringPtrInput
	// The ID of the SSH Certificate Authority used for SSH access.
	SshCaId pulumi.StringPtrInput
	// The ID of the X.509 Certificate Authority used for TLS.
	X509CaId pulumi.StringPtrInput
}

func (TwingateGatewayState) ElementType() reflect.Type {
	return reflect.TypeOf((*twingateGatewayState)(nil)).Elem()
}

type twingateGatewayArgs struct {
	// The address of the Gateway.
	Address string `pulumi:"address"`
	// The ID of the Remote Network the Gateway belongs to.
	RemoteNetworkId string `pulumi:"remoteNetworkId"`
	// The ID of the SSH Certificate Authority used for SSH access.
	SshCaId *string `pulumi:"sshCaId"`
	// The ID of the X.509 Certificate Authority used for TLS.
	X509CaId string `pulumi:"x509CaId"`
}

// The set of arguments for constructing a TwingateGateway resource.
type TwingateGatewayArgs struct {
	// The address of the Gateway.
	Address pulumi.StringInput
	// The ID of the Remote Network the Gateway belongs to.
	RemoteNetworkId pulumi.StringInput
	// The ID of the SSH Certificate Authority used for SSH access.
	SshCaId pulumi.StringPtrInput
	// The ID of the X.509 Certificate Authority used for TLS.
	X509CaId pulumi.StringInput
}

func (TwingateGatewayArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*twingateGatewayArgs)(nil)).Elem()
}

type TwingateGatewayInput interface {
	pulumi.Input

	ToTwingateGatewayOutput() TwingateGatewayOutput
	ToTwingateGatewayOutputWithContext(ctx context.Context) TwingateGatewayOutput
}

func (*TwingateGateway) ElementType() reflect.Type {
	return reflect.TypeOf((**TwingateGateway)(nil)).Elem()
}

func (i *TwingateGateway) ToTwingateGatewayOutput() TwingateGatewayOutput {
	return i.ToTwingateGatewayOutputWithContext(context.Background())
}

func (i *TwingateGateway) ToTwingateGatewayOutputWithContext(ctx context.Context) TwingateGatewayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TwingateGatewayOutput)
}

// TwingateGatewayArrayInput is an input type that accepts TwingateGatewayArray and TwingateGatewayArrayOutput values.
// You can construct a concrete instance of `TwingateGatewayArrayInput` via:
//
//	TwingateGatewayArray{ TwingateGatewayArgs{...} }
type TwingateGatewayArrayInput interface {
	pulumi.Input

	ToTwingateGatewayArrayOutput() TwingateGatewayArrayOutput
	ToTwingateGatewayArrayOutputWithContext(context.Context) TwingateGatewayArrayOutput
}

type TwingateGatewayArray []TwingateGatewayInput

func (TwingateGatewayArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TwingateGateway)(nil)).Elem()
}

func (i TwingateGatewayArray) ToTwingateGatewayArrayOutput() TwingateGatewayArrayOutput {
	return i.ToTwingateGatewayArrayOutputWithContext(context.Background())
}

func (i TwingateGatewayArray) ToTwingateGatewayArrayOutputWithContext(ctx context.Context) TwingateGatewayArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TwingateGatewayArrayOutput)
}

// TwingateGatewayMapInput is an input type that accepts TwingateGatewayMap and TwingateGatewayMapOutput values.
// You can construct a concrete instance of `TwingateGatewayMapInput` via:
//
//	TwingateGatewayMap{ "key": TwingateGatewayArgs{...} }
type TwingateGatewayMapInput interface {
	pulumi.Input

	ToTwingateGatewayMapOutput() TwingateGatewayMapOutput
	ToTwingateGatewayMapOutputWithContext(context.Context) TwingateGatewayMapOutput
}

type TwingateGatewayMap map[string]TwingateGatewayInput

func (TwingateGatewayMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TwingateGateway)(nil)).Elem()
}

func (i TwingateGatewayMap) ToTwingateGatewayMapOutput() TwingateGatewayMapOutput {
	return i.ToTwingateGatewayMapOutputWithContext(context.Background())
}

func (i TwingateGatewayMap) ToTwingateGatewayMapOutputWithContext(ctx context.Context) TwingateGatewayMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TwingateGatewayMapOutput)
}

type TwingateGatewayOutput struct{ *pulumi.OutputState }

func (TwingateGatewayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TwingateGateway)(nil)).Elem()
}

func (o TwingateGatewayOutput) ToTwingateGatewayOutput() TwingateGatewayOutput {
	return o
}

func (o TwingateGatewayOutput) ToTwingateGatewayOutputWithContext(ctx context.Context) TwingateGatewayOutput {
	return o
}

// The address of the Gateway.
func (o TwingateGatewayOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v *TwingateGateway) pulumi.StringOutput { return v.Address }).(pulumi.StringOutput)
}

// The ID of the Remote Network the Gateway belongs to.
func (o TwingateGatewayOutput) RemoteNetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v *TwingateGateway) pulumi.StringOutput { return v.RemoteNetworkId }).(pulumi.StringOutput)
}

// The ID of the SSH Certificate Authority used for SSH access.
func (o TwingateGatewayOutput) SshCaId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TwingateGateway) pulumi.StringPtrOutput { return v.SshCaId }).(pulumi.StringPtrOutput)
}

// The ID of the X.509 Certificate Authority used for TLS.
func (o TwingateGatewayOutput) X509CaId() pulumi.StringOutput {
	return o.ApplyT(func(v *TwingateGateway) pulumi.StringOutput { return v.X509CaId }).(pulumi.StringOutput)
}

type TwingateGatewayArrayOutput struct{ *pulumi.OutputState }

func (TwingateGatewayArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TwingateGateway)(nil)).Elem()
}

func (o TwingateGatewayArrayOutput) ToTwingateGatewayArrayOutput() TwingateGatewayArrayOutput {
	return o
}

func (o TwingateGatewayArrayOutput) ToTwingateGatewayArrayOutputWithContext(ctx context.Context) TwingateGatewayArrayOutput {
	return o
}

func (o TwingateGatewayArrayOutput) Index(i pulumi.IntInput) TwingateGatewayOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *TwingateGateway {
		return vs[0].([]*TwingateGateway)[vs[1].(int)]
	}).(TwingateGatewayOutput)
}

type TwingateGatewayMapOutput struct{ *pulumi.OutputState }

func (TwingateGatewayMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TwingateGateway)(nil)).Elem()
}

func (o TwingateGatewayMapOutput) ToTwingateGatewayMapOutput() TwingateGatewayMapOutput {
	return o
}

func (o TwingateGatewayMapOutput) ToTwingateGatewayMapOutputWithContext(ctx context.Context) TwingateGatewayMapOutput {
	return o
}

func (o TwingateGatewayMapOutput) MapIndex(k pulumi.StringInput) TwingateGatewayOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *TwingateGateway {
		return vs[0].(map[string]*TwingateGateway)[vs[1].(string)]
	}).(TwingateGatewayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TwingateGatewayInput)(nil)).Elem(), &TwingateGateway{})
	pulumi.RegisterInputType(reflect.TypeOf((*TwingateGatewayArrayInput)(nil)).Elem(), TwingateGatewayArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TwingateGatewayMapInput)(nil)).Elem(), TwingateGatewayMap{})
	pulumi.RegisterOutputType(TwingateGatewayOutput{})
	pulumi.RegisterOutputType(TwingateGatewayArrayOutput{})
	pulumi.RegisterOutputType(TwingateGatewayMapOutput{})
}
