archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make tfgen
builds:
  - binary: pulumi-resource-twingate
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    hooks:
      post: []
    ignore: []
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/Twingate/pulumi-twingate/provider/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-twingate/
changelog:
  disable: true
release:
  disable: false
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
project_name: "pulumi-twingate"
