// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate
{
    public static class GetTwingateRemoteNetwork
    {
        /// <summary>
        /// A Remote Network represents a single private network in Twingate that can have one or more Connectors and Resources assigned to it. You must create a Remote Network before creating Resources and Connectors that belong to it. For more information, see Twingate's [documentation](https://docs.twingate.com/docs/remote-networks).
        /// </summary>
        public static Task<GetTwingateRemoteNetworkResult> InvokeAsync(GetTwingateRemoteNetworkArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTwingateRemoteNetworkResult>("twingate:index/getTwingateRemoteNetwork:getTwingateRemoteNetwork", args ?? new GetTwingateRemoteNetworkArgs(), options.WithDefaults());

        /// <summary>
        /// A Remote Network represents a single private network in Twingate that can have one or more Connectors and Resources assigned to it. You must create a Remote Network before creating Resources and Connectors that belong to it. For more information, see Twingate's [documentation](https://docs.twingate.com/docs/remote-networks).
        /// </summary>
        public static Output<GetTwingateRemoteNetworkResult> Invoke(GetTwingateRemoteNetworkInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTwingateRemoteNetworkResult>("twingate:index/getTwingateRemoteNetwork:getTwingateRemoteNetwork", args ?? new GetTwingateRemoteNetworkInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// A Remote Network represents a single private network in Twingate that can have one or more Connectors and Resources assigned to it. You must create a Remote Network before creating Resources and Connectors that belong to it. For more information, see Twingate's [documentation](https://docs.twingate.com/docs/remote-networks).
        /// </summary>
        public static Output<GetTwingateRemoteNetworkResult> Invoke(GetTwingateRemoteNetworkInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTwingateRemoteNetworkResult>("twingate:index/getTwingateRemoteNetwork:getTwingateRemoteNetwork", args ?? new GetTwingateRemoteNetworkInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTwingateRemoteNetworkArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the Remote Network
        /// </summary>
        [Input("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The name of the Remote Network
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetTwingateRemoteNetworkArgs()
        {
        }
        public static new GetTwingateRemoteNetworkArgs Empty => new GetTwingateRemoteNetworkArgs();
    }

    public sealed class GetTwingateRemoteNetworkInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the Remote Network
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// The name of the Remote Network
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetTwingateRemoteNetworkInvokeArgs()
        {
        }
        public static new GetTwingateRemoteNetworkInvokeArgs Empty => new GetTwingateRemoteNetworkInvokeArgs();
    }


    [OutputType]
    public sealed class GetTwingateRemoteNetworkResult
    {
        /// <summary>
        /// The ID of the Remote Network
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The location of the Remote Network. Must be one of the following: AWS, AZURE, GOOGLE*CLOUD, ON*PREMISE, OTHER.
        /// </summary>
        public readonly string Location;
        /// <summary>
        /// The name of the Remote Network
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The type of the Remote Network. Must be one of the following: REGULAR, EXIT.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetTwingateRemoteNetworkResult(
            string? id,

            string location,

            string? name,

            string type)
        {
            Id = id;
            Location = location;
            Name = name;
            Type = type;
        }
    }
}
