// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate
{
    /// <summary>
    /// A Remote Network represents a single private network in Twingate that can have one or more Connectors and Resources assigned to it. You must create a Remote Network before creating Resources and Connectors that belong to it. For more information, see Twingate's [documentation](https://docs.twingate.com/docs/remote-networks).
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Twingate = Twingate.Twingate;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var awsNetwork = new Twingate.TwingateRemoteNetwork("aws_network", new()
    ///     {
    ///         Name = "aws_remote_network",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    /// $ pulumi import twingate:index/twingateRemoteNetwork:TwingateRemoteNetwork network UmVtb3RlTmV0d29zaipgMKIkNg==
    /// ```
    /// </summary>
    [TwingateResourceType("twingate:index/twingateRemoteNetwork:TwingateRemoteNetwork")]
    public partial class TwingateRemoteNetwork : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The location of the Remote Network. Must be one of the following: AWS, AZURE, GOOGLE*CLOUD, ON*PREMISE, OTHER.
        /// </summary>
        [Output("location")]
        public Output<string> Location { get; private set; } = null!;

        /// <summary>
        /// The name of the Remote Network
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The type of the Remote Network. Must be one of the following: REGULAR, EXIT. Defaults to REGULAR.
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;


        /// <summary>
        /// Create a TwingateRemoteNetwork resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TwingateRemoteNetwork(string name, TwingateRemoteNetworkArgs? args = null, CustomResourceOptions? options = null)
            : base("twingate:index/twingateRemoteNetwork:TwingateRemoteNetwork", name, args ?? new TwingateRemoteNetworkArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TwingateRemoteNetwork(string name, Input<string> id, TwingateRemoteNetworkState? state = null, CustomResourceOptions? options = null)
            : base("twingate:index/twingateRemoteNetwork:TwingateRemoteNetwork", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/Twingate/pulumi-twingate",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TwingateRemoteNetwork resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TwingateRemoteNetwork Get(string name, Input<string> id, TwingateRemoteNetworkState? state = null, CustomResourceOptions? options = null)
        {
            return new TwingateRemoteNetwork(name, id, state, options);
        }
    }

    public sealed class TwingateRemoteNetworkArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The location of the Remote Network. Must be one of the following: AWS, AZURE, GOOGLE*CLOUD, ON*PREMISE, OTHER.
        /// </summary>
        [Input("location")]
        public Input<string>? Location { get; set; }

        /// <summary>
        /// The name of the Remote Network
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The type of the Remote Network. Must be one of the following: REGULAR, EXIT. Defaults to REGULAR.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public TwingateRemoteNetworkArgs()
        {
        }
        public static new TwingateRemoteNetworkArgs Empty => new TwingateRemoteNetworkArgs();
    }

    public sealed class TwingateRemoteNetworkState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The location of the Remote Network. Must be one of the following: AWS, AZURE, GOOGLE*CLOUD, ON*PREMISE, OTHER.
        /// </summary>
        [Input("location")]
        public Input<string>? Location { get; set; }

        /// <summary>
        /// The name of the Remote Network
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The type of the Remote Network. Must be one of the following: REGULAR, EXIT. Defaults to REGULAR.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public TwingateRemoteNetworkState()
        {
        }
        public static new TwingateRemoteNetworkState Empty => new TwingateRemoteNetworkState();
    }
}
