// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate
{
    /// <summary>
    /// Kubernetes Resources are Twingate resources accessed via a Gateway.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Std = Pulumi.Std;
    /// using Twingate = Twingate.Twingate;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var prod = new Twingate.TwingateRemoteNetwork("prod", new()
    ///     {
    ///         Name = "Production Network",
    ///     });
    /// 
    ///     var tls = new Twingate.TwingateX509CertificateAuthority("tls", new()
    ///     {
    ///         Name = "My TLS CA",
    ///         Certificate = Std.File.Invoke(new()
    ///         {
    ///             Input = "ca.pem",
    ///         }).Apply(invoke =&gt; invoke.Result),
    ///     });
    /// 
    ///     var main = new Twingate.TwingateGateway("main", new()
    ///     {
    ///         RemoteNetworkId = prod.Id,
    ///         Address = "10.0.0.1:8443",
    ///         X509CaId = tls.Id,
    ///     });
    /// 
    ///     // Kubernetes resource accessed via in-cluster DNS
    ///     var prodCluster = new Twingate.TwingateKubernetesResource("prod_cluster", new()
    ///     {
    ///         Name = "Production K8s",
    ///         GatewayId = main.Id,
    ///         RemoteNetworkId = prod.Id,
    ///     });
    /// 
    ///     // Kubernetes resource accessed via external address
    ///     var externalCluster = new Twingate.TwingateKubernetesResource("external_cluster", new()
    ///     {
    ///         Name = "External K8s",
    ///         Address = "k8s-api.example.com",
    ///         GatewayId = main.Id,
    ///         RemoteNetworkId = prod.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [TwingateResourceType("twingate:index/twingateKubernetesResource:TwingateKubernetesResource")]
    public partial class TwingateKubernetesResource : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Restrict access to certain group
        /// </summary>
        [Output("accessGroups")]
        public Output<ImmutableArray<Outputs.TwingateKubernetesResourceAccessGroup>> AccessGroups { get; private set; } = null!;

        /// <summary>
        /// Restrict access according to JIT access policy
        /// </summary>
        [Output("accessPolicies")]
        public Output<ImmutableArray<Outputs.TwingateKubernetesResourceAccessPolicy>> AccessPolicies { get; private set; } = null!;

        /// <summary>
        /// The address of the Kubernetes Resource (IP or FQDN).
        /// </summary>
        [Output("address")]
        public Output<string> Address { get; private set; } = null!;

        /// <summary>
        /// Set a DNS alias address for the Resource. Must be a DNS-valid name string.
        /// </summary>
        [Output("alias")]
        public Output<string?> Alias { get; private set; } = null!;

        /// <summary>
        /// Path to bearer token file.
        /// </summary>
        [Output("bearerTokenFile")]
        public Output<string> BearerTokenFile { get; private set; } = null!;

        /// <summary>
        /// Path to CA certificate file.
        /// </summary>
        [Output("caFile")]
        public Output<string> CaFile { get; private set; } = null!;

        /// <summary>
        /// The ID of the Gateway used to access this Kubernetes Resource.
        /// </summary>
        [Output("gatewayId")]
        public Output<string> GatewayId { get; private set; } = null!;

        /// <summary>
        /// Whether the Gateway is running inside the same Kubernetes cluster that is represented by the Kubernetes Resource. Default is `True`.
        /// </summary>
        [Output("inCluster")]
        public Output<bool> InCluster { get; private set; } = null!;

        /// <summary>
        /// Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `True`.
        /// </summary>
        [Output("isVisible")]
        public Output<bool> IsVisible { get; private set; } = null!;

        /// <summary>
        /// The name of the Kubernetes Resource.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Restrict access to certain protocols and ports. By default or when this argument is not defined, there is no restriction, and all protocols and ports are allowed.
        /// </summary>
        [Output("protocols")]
        public Output<Outputs.TwingateKubernetesResourceProtocols> Protocols { get; private set; } = null!;

        /// <summary>
        /// The ID of the Remote Network the Kubernetes Resource belongs to.
        /// </summary>
        [Output("remoteNetworkId")]
        public Output<string> RemoteNetworkId { get; private set; } = null!;

        /// <summary>
        /// The ID of a `twingate.getTwingateSecurityPolicy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.
        /// </summary>
        [Output("securityPolicyId")]
        public Output<string> SecurityPolicyId { get; private set; } = null!;

        /// <summary>
        /// A map of key-value pair tags to set on this resource.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableDictionary<string, string>> Tags { get; private set; } = null!;


        /// <summary>
        /// Create a TwingateKubernetesResource resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TwingateKubernetesResource(string name, TwingateKubernetesResourceArgs args, CustomResourceOptions? options = null)
            : base("twingate:index/twingateKubernetesResource:TwingateKubernetesResource", name, args ?? new TwingateKubernetesResourceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TwingateKubernetesResource(string name, Input<string> id, TwingateKubernetesResourceState? state = null, CustomResourceOptions? options = null)
            : base("twingate:index/twingateKubernetesResource:TwingateKubernetesResource", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/Twingate/pulumi-twingate",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TwingateKubernetesResource resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TwingateKubernetesResource Get(string name, Input<string> id, TwingateKubernetesResourceState? state = null, CustomResourceOptions? options = null)
        {
            return new TwingateKubernetesResource(name, id, state, options);
        }
    }

    public sealed class TwingateKubernetesResourceArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessGroups")]
        private InputList<Inputs.TwingateKubernetesResourceAccessGroupArgs>? _accessGroups;

        /// <summary>
        /// Restrict access to certain group
        /// </summary>
        public InputList<Inputs.TwingateKubernetesResourceAccessGroupArgs> AccessGroups
        {
            get => _accessGroups ?? (_accessGroups = new InputList<Inputs.TwingateKubernetesResourceAccessGroupArgs>());
            set => _accessGroups = value;
        }

        [Input("accessPolicies")]
        private InputList<Inputs.TwingateKubernetesResourceAccessPolicyArgs>? _accessPolicies;

        /// <summary>
        /// Restrict access according to JIT access policy
        /// </summary>
        public InputList<Inputs.TwingateKubernetesResourceAccessPolicyArgs> AccessPolicies
        {
            get => _accessPolicies ?? (_accessPolicies = new InputList<Inputs.TwingateKubernetesResourceAccessPolicyArgs>());
            set => _accessPolicies = value;
        }

        /// <summary>
        /// The address of the Kubernetes Resource (IP or FQDN).
        /// </summary>
        [Input("address")]
        public Input<string>? Address { get; set; }

        /// <summary>
        /// Set a DNS alias address for the Resource. Must be a DNS-valid name string.
        /// </summary>
        [Input("alias")]
        public Input<string>? Alias { get; set; }

        /// <summary>
        /// Path to bearer token file.
        /// </summary>
        [Input("bearerTokenFile")]
        public Input<string>? BearerTokenFile { get; set; }

        /// <summary>
        /// Path to CA certificate file.
        /// </summary>
        [Input("caFile")]
        public Input<string>? CaFile { get; set; }

        /// <summary>
        /// The ID of the Gateway used to access this Kubernetes Resource.
        /// </summary>
        [Input("gatewayId", required: true)]
        public Input<string> GatewayId { get; set; } = null!;

        /// <summary>
        /// Whether the Gateway is running inside the same Kubernetes cluster that is represented by the Kubernetes Resource. Default is `True`.
        /// </summary>
        [Input("inCluster")]
        public Input<bool>? InCluster { get; set; }

        /// <summary>
        /// Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `True`.
        /// </summary>
        [Input("isVisible")]
        public Input<bool>? IsVisible { get; set; }

        /// <summary>
        /// The name of the Kubernetes Resource.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Restrict access to certain protocols and ports. By default or when this argument is not defined, there is no restriction, and all protocols and ports are allowed.
        /// </summary>
        [Input("protocols")]
        public Input<Inputs.TwingateKubernetesResourceProtocolsArgs>? Protocols { get; set; }

        /// <summary>
        /// The ID of the Remote Network the Kubernetes Resource belongs to.
        /// </summary>
        [Input("remoteNetworkId", required: true)]
        public Input<string> RemoteNetworkId { get; set; } = null!;

        /// <summary>
        /// The ID of a `twingate.getTwingateSecurityPolicy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.
        /// </summary>
        [Input("securityPolicyId")]
        public Input<string>? SecurityPolicyId { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// A map of key-value pair tags to set on this resource.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        public TwingateKubernetesResourceArgs()
        {
        }
        public static new TwingateKubernetesResourceArgs Empty => new TwingateKubernetesResourceArgs();
    }

    public sealed class TwingateKubernetesResourceState : global::Pulumi.ResourceArgs
    {
        [Input("accessGroups")]
        private InputList<Inputs.TwingateKubernetesResourceAccessGroupGetArgs>? _accessGroups;

        /// <summary>
        /// Restrict access to certain group
        /// </summary>
        public InputList<Inputs.TwingateKubernetesResourceAccessGroupGetArgs> AccessGroups
        {
            get => _accessGroups ?? (_accessGroups = new InputList<Inputs.TwingateKubernetesResourceAccessGroupGetArgs>());
            set => _accessGroups = value;
        }

        [Input("accessPolicies")]
        private InputList<Inputs.TwingateKubernetesResourceAccessPolicyGetArgs>? _accessPolicies;

        /// <summary>
        /// Restrict access according to JIT access policy
        /// </summary>
        public InputList<Inputs.TwingateKubernetesResourceAccessPolicyGetArgs> AccessPolicies
        {
            get => _accessPolicies ?? (_accessPolicies = new InputList<Inputs.TwingateKubernetesResourceAccessPolicyGetArgs>());
            set => _accessPolicies = value;
        }

        /// <summary>
        /// The address of the Kubernetes Resource (IP or FQDN).
        /// </summary>
        [Input("address")]
        public Input<string>? Address { get; set; }

        /// <summary>
        /// Set a DNS alias address for the Resource. Must be a DNS-valid name string.
        /// </summary>
        [Input("alias")]
        public Input<string>? Alias { get; set; }

        /// <summary>
        /// Path to bearer token file.
        /// </summary>
        [Input("bearerTokenFile")]
        public Input<string>? BearerTokenFile { get; set; }

        /// <summary>
        /// Path to CA certificate file.
        /// </summary>
        [Input("caFile")]
        public Input<string>? CaFile { get; set; }

        /// <summary>
        /// The ID of the Gateway used to access this Kubernetes Resource.
        /// </summary>
        [Input("gatewayId")]
        public Input<string>? GatewayId { get; set; }

        /// <summary>
        /// Whether the Gateway is running inside the same Kubernetes cluster that is represented by the Kubernetes Resource. Default is `True`.
        /// </summary>
        [Input("inCluster")]
        public Input<bool>? InCluster { get; set; }

        /// <summary>
        /// Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `True`.
        /// </summary>
        [Input("isVisible")]
        public Input<bool>? IsVisible { get; set; }

        /// <summary>
        /// The name of the Kubernetes Resource.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Restrict access to certain protocols and ports. By default or when this argument is not defined, there is no restriction, and all protocols and ports are allowed.
        /// </summary>
        [Input("protocols")]
        public Input<Inputs.TwingateKubernetesResourceProtocolsGetArgs>? Protocols { get; set; }

        /// <summary>
        /// The ID of the Remote Network the Kubernetes Resource belongs to.
        /// </summary>
        [Input("remoteNetworkId")]
        public Input<string>? RemoteNetworkId { get; set; }

        /// <summary>
        /// The ID of a `twingate.getTwingateSecurityPolicy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.
        /// </summary>
        [Input("securityPolicyId")]
        public Input<string>? SecurityPolicyId { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// A map of key-value pair tags to set on this resource.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        public TwingateKubernetesResourceState()
        {
        }
        public static new TwingateKubernetesResourceState Empty => new TwingateKubernetesResourceState();
    }
}
