# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

import types

__config__ = pulumi.Config('twingate')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def api_token(self) -> Optional[str]:
        """
        The access key for API operations. You can retrieve this
        from the Twingate Admin Console ([documentation](https://docs.twingate.com/docs/api-overview)).
        Alternatively, this can be specified using the TWINGATE_API_TOKEN environment variable.
        """
        return __config__.get('apiToken')

    @_builtins.property
    def cache(self) -> Optional[str]:
        """
        Specifies the cache settings for the provider.
        """
        return __config__.get('cache')

    @_builtins.property
    def default_tags(self) -> Optional[str]:
        """
        A default set of tags applied globally to all resources created by the provider.
        """
        return __config__.get('defaultTags')

    @_builtins.property
    def http_max_retry(self) -> Optional[int]:
        """
        Specifies a retry limit for the http requests made. The default value is 10.
        Alternatively, this can be specified using the TWINGATE_HTTP_MAX_RETRY environment variable
        """
        return __config__.get_int('httpMaxRetry')

    @_builtins.property
    def http_timeout(self) -> Optional[int]:
        """
        Specifies a time limit in seconds for the http requests made. The default value is 35 seconds.
        Alternatively, this can be specified using the TWINGATE_HTTP_TIMEOUT environment variable
        """
        return __config__.get_int('httpTimeout')

    @_builtins.property
    def network(self) -> Optional[str]:
        """
        Your Twingate network ID for API operations.
        You can find it in the Admin Console URL, for example:
        `autoco.twingate.com`, where `autoco` is your network ID
        Alternatively, this can be specified using the TWINGATE_NETWORK environment variable.
        """
        return __config__.get('network')

    @_builtins.property
    def url(self) -> Optional[str]:
        """
        The default is 'twingate.com'
        This is optional and shouldn't be changed under normal circumstances.
        """
        return __config__.get('url')

