# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetTwingateSSHCertificateAuthorityResult',
    'AwaitableGetTwingateSSHCertificateAuthorityResult',
    'get_twingate_ssh_certificate_authority',
    'get_twingate_ssh_certificate_authority_output',
]

@pulumi.output_type
class GetTwingateSSHCertificateAuthorityResult:
    """
    A collection of values returned by getTwingateSSHCertificateAuthority.
    """
    def __init__(__self__, fingerprint=None, id=None, name=None):
        if fingerprint and not isinstance(fingerprint, str):
            raise TypeError("Expected argument 'fingerprint' to be a str")
        pulumi.set(__self__, "fingerprint", fingerprint)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def fingerprint(self) -> _builtins.str:
        """
        The fingerprint of the SSH public key.
        """
        return pulumi.get(self, "fingerprint")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The ID of the SSH Certificate Authority.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the SSH Certificate Authority.
        """
        return pulumi.get(self, "name")


class AwaitableGetTwingateSSHCertificateAuthorityResult(GetTwingateSSHCertificateAuthorityResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetTwingateSSHCertificateAuthorityResult(
            fingerprint=self.fingerprint,
            id=self.id,
            name=self.name)


def get_twingate_ssh_certificate_authority(id: Optional[_builtins.str] = None,
                                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetTwingateSSHCertificateAuthorityResult:
    """
    SSH Certificate Authorities allow Twingate to sign SSH certificates for authenticating users to resources.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_twingate as twingate

    example = twingate.get_twingate_ssh_certificate_authority(id="<your ssh certificate authority's id>")
    ```


    :param _builtins.str id: The ID of the SSH Certificate Authority.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('twingate:index/getTwingateSSHCertificateAuthority:getTwingateSSHCertificateAuthority', __args__, opts=opts, typ=GetTwingateSSHCertificateAuthorityResult).value

    return AwaitableGetTwingateSSHCertificateAuthorityResult(
        fingerprint=pulumi.get(__ret__, 'fingerprint'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'))
def get_twingate_ssh_certificate_authority_output(id: Optional[pulumi.Input[_builtins.str]] = None,
                                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetTwingateSSHCertificateAuthorityResult]:
    """
    SSH Certificate Authorities allow Twingate to sign SSH certificates for authenticating users to resources.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_twingate as twingate

    example = twingate.get_twingate_ssh_certificate_authority(id="<your ssh certificate authority's id>")
    ```


    :param _builtins.str id: The ID of the SSH Certificate Authority.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('twingate:index/getTwingateSSHCertificateAuthority:getTwingateSSHCertificateAuthority', __args__, opts=opts, typ=GetTwingateSSHCertificateAuthorityResult)
    return __ret__.apply(lambda __response__: GetTwingateSSHCertificateAuthorityResult(
        fingerprint=pulumi.get(__response__, 'fingerprint'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name')))
