# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetTwingateConnectorsResult',
    'AwaitableGetTwingateConnectorsResult',
    'get_twingate_connectors',
    'get_twingate_connectors_output',
]

@pulumi.output_type
class GetTwingateConnectorsResult:
    """
    A collection of values returned by getTwingateConnectors.
    """
    def __init__(__self__, connectors=None, id=None, name=None, name_contains=None, name_exclude=None, name_prefix=None, name_regexp=None, name_suffix=None):
        if connectors and not isinstance(connectors, list):
            raise TypeError("Expected argument 'connectors' to be a list")
        pulumi.set(__self__, "connectors", connectors)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if name_contains and not isinstance(name_contains, str):
            raise TypeError("Expected argument 'name_contains' to be a str")
        pulumi.set(__self__, "name_contains", name_contains)
        if name_exclude and not isinstance(name_exclude, str):
            raise TypeError("Expected argument 'name_exclude' to be a str")
        pulumi.set(__self__, "name_exclude", name_exclude)
        if name_prefix and not isinstance(name_prefix, str):
            raise TypeError("Expected argument 'name_prefix' to be a str")
        pulumi.set(__self__, "name_prefix", name_prefix)
        if name_regexp and not isinstance(name_regexp, str):
            raise TypeError("Expected argument 'name_regexp' to be a str")
        pulumi.set(__self__, "name_regexp", name_regexp)
        if name_suffix and not isinstance(name_suffix, str):
            raise TypeError("Expected argument 'name_suffix' to be a str")
        pulumi.set(__self__, "name_suffix", name_suffix)

    @_builtins.property
    @pulumi.getter
    def connectors(self) -> Sequence['outputs.GetTwingateConnectorsConnectorResult']:
        """
        List of Connectors
        """
        return pulumi.get(self, "connectors")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The ID of this resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        """
        Returns only connectors that exactly match this name. If no options are passed it will return all connectors. Only one option can be used at a time.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="nameContains")
    def name_contains(self) -> Optional[_builtins.str]:
        """
        Match when the value exist in the name of the connector.
        """
        return pulumi.get(self, "name_contains")

    @_builtins.property
    @pulumi.getter(name="nameExclude")
    def name_exclude(self) -> Optional[_builtins.str]:
        """
        Match when the exact value does not exist in the name of the connector.
        """
        return pulumi.get(self, "name_exclude")

    @_builtins.property
    @pulumi.getter(name="namePrefix")
    def name_prefix(self) -> Optional[_builtins.str]:
        """
        The name of the connector must start with the value.
        """
        return pulumi.get(self, "name_prefix")

    @_builtins.property
    @pulumi.getter(name="nameRegexp")
    def name_regexp(self) -> Optional[_builtins.str]:
        """
        The regular expression match of the name of the connector.
        """
        return pulumi.get(self, "name_regexp")

    @_builtins.property
    @pulumi.getter(name="nameSuffix")
    def name_suffix(self) -> Optional[_builtins.str]:
        """
        The name of the connector must end with the value.
        """
        return pulumi.get(self, "name_suffix")


class AwaitableGetTwingateConnectorsResult(GetTwingateConnectorsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetTwingateConnectorsResult(
            connectors=self.connectors,
            id=self.id,
            name=self.name,
            name_contains=self.name_contains,
            name_exclude=self.name_exclude,
            name_prefix=self.name_prefix,
            name_regexp=self.name_regexp,
            name_suffix=self.name_suffix)


def get_twingate_connectors(name: Optional[_builtins.str] = None,
                            name_contains: Optional[_builtins.str] = None,
                            name_exclude: Optional[_builtins.str] = None,
                            name_prefix: Optional[_builtins.str] = None,
                            name_regexp: Optional[_builtins.str] = None,
                            name_suffix: Optional[_builtins.str] = None,
                            opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetTwingateConnectorsResult:
    """
    Connectors provide connectivity to Remote Networks. For more information, see Twingate's [documentation](https://docs.twingate.com/docs/understanding-access-nodes).

    ## Example Usage

    ```python
    import pulumi
    import pulumi_twingate as twingate

    all = twingate.get_twingate_connectors(name="<your connector's name>")
    ```


    :param _builtins.str name: Returns only connectors that exactly match this name. If no options are passed it will return all connectors. Only one option can be used at a time.
    :param _builtins.str name_contains: Match when the value exist in the name of the connector.
    :param _builtins.str name_exclude: Match when the exact value does not exist in the name of the connector.
    :param _builtins.str name_prefix: The name of the connector must start with the value.
    :param _builtins.str name_regexp: The regular expression match of the name of the connector.
    :param _builtins.str name_suffix: The name of the connector must end with the value.
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['nameContains'] = name_contains
    __args__['nameExclude'] = name_exclude
    __args__['namePrefix'] = name_prefix
    __args__['nameRegexp'] = name_regexp
    __args__['nameSuffix'] = name_suffix
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('twingate:index/getTwingateConnectors:getTwingateConnectors', __args__, opts=opts, typ=GetTwingateConnectorsResult).value

    return AwaitableGetTwingateConnectorsResult(
        connectors=pulumi.get(__ret__, 'connectors'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        name_contains=pulumi.get(__ret__, 'name_contains'),
        name_exclude=pulumi.get(__ret__, 'name_exclude'),
        name_prefix=pulumi.get(__ret__, 'name_prefix'),
        name_regexp=pulumi.get(__ret__, 'name_regexp'),
        name_suffix=pulumi.get(__ret__, 'name_suffix'))
def get_twingate_connectors_output(name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                   name_contains: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                   name_exclude: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                   name_prefix: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                   name_regexp: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                   name_suffix: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                   opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetTwingateConnectorsResult]:
    """
    Connectors provide connectivity to Remote Networks. For more information, see Twingate's [documentation](https://docs.twingate.com/docs/understanding-access-nodes).

    ## Example Usage

    ```python
    import pulumi
    import pulumi_twingate as twingate

    all = twingate.get_twingate_connectors(name="<your connector's name>")
    ```


    :param _builtins.str name: Returns only connectors that exactly match this name. If no options are passed it will return all connectors. Only one option can be used at a time.
    :param _builtins.str name_contains: Match when the value exist in the name of the connector.
    :param _builtins.str name_exclude: Match when the exact value does not exist in the name of the connector.
    :param _builtins.str name_prefix: The name of the connector must start with the value.
    :param _builtins.str name_regexp: The regular expression match of the name of the connector.
    :param _builtins.str name_suffix: The name of the connector must end with the value.
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['nameContains'] = name_contains
    __args__['nameExclude'] = name_exclude
    __args__['namePrefix'] = name_prefix
    __args__['nameRegexp'] = name_regexp
    __args__['nameSuffix'] = name_suffix
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('twingate:index/getTwingateConnectors:getTwingateConnectors', __args__, opts=opts, typ=GetTwingateConnectorsResult)
    return __ret__.apply(lambda __response__: GetTwingateConnectorsResult(
        connectors=pulumi.get(__response__, 'connectors'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        name_contains=pulumi.get(__response__, 'name_contains'),
        name_exclude=pulumi.get(__response__, 'name_exclude'),
        name_prefix=pulumi.get(__response__, 'name_prefix'),
        name_regexp=pulumi.get(__response__, 'name_regexp'),
        name_suffix=pulumi.get(__response__, 'name_suffix')))
