# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['TwingateGatewayArgs', 'TwingateGateway']

@pulumi.input_type
class TwingateGatewayArgs:
    def __init__(__self__, *,
                 address: pulumi.Input[_builtins.str],
                 remote_network_id: pulumi.Input[_builtins.str],
                 x509_ca_id: pulumi.Input[_builtins.str],
                 ssh_ca_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a TwingateGateway resource.

        :param pulumi.Input[_builtins.str] address: The address of the Gateway.
        :param pulumi.Input[_builtins.str] remote_network_id: The ID of the Remote Network the Gateway belongs to.
        :param pulumi.Input[_builtins.str] x509_ca_id: The ID of the X.509 Certificate Authority used for TLS.
        :param pulumi.Input[_builtins.str] ssh_ca_id: The ID of the SSH Certificate Authority used for SSH access.
        """
        pulumi.set(__self__, "address", address)
        pulumi.set(__self__, "remote_network_id", remote_network_id)
        pulumi.set(__self__, "x509_ca_id", x509_ca_id)
        if ssh_ca_id is not None:
            pulumi.set(__self__, "ssh_ca_id", ssh_ca_id)

    @_builtins.property
    @pulumi.getter
    def address(self) -> pulumi.Input[_builtins.str]:
        """
        The address of the Gateway.
        """
        return pulumi.get(self, "address")

    @address.setter
    def address(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "address", value)

    @_builtins.property
    @pulumi.getter(name="remoteNetworkId")
    def remote_network_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the Remote Network the Gateway belongs to.
        """
        return pulumi.get(self, "remote_network_id")

    @remote_network_id.setter
    def remote_network_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "remote_network_id", value)

    @_builtins.property
    @pulumi.getter(name="x509CaId")
    def x509_ca_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the X.509 Certificate Authority used for TLS.
        """
        return pulumi.get(self, "x509_ca_id")

    @x509_ca_id.setter
    def x509_ca_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "x509_ca_id", value)

    @_builtins.property
    @pulumi.getter(name="sshCaId")
    def ssh_ca_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the SSH Certificate Authority used for SSH access.
        """
        return pulumi.get(self, "ssh_ca_id")

    @ssh_ca_id.setter
    def ssh_ca_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ssh_ca_id", value)


@pulumi.input_type
class _TwingateGatewayState:
    def __init__(__self__, *,
                 address: Optional[pulumi.Input[_builtins.str]] = None,
                 remote_network_id: Optional[pulumi.Input[_builtins.str]] = None,
                 ssh_ca_id: Optional[pulumi.Input[_builtins.str]] = None,
                 x509_ca_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering TwingateGateway resources.

        :param pulumi.Input[_builtins.str] address: The address of the Gateway.
        :param pulumi.Input[_builtins.str] remote_network_id: The ID of the Remote Network the Gateway belongs to.
        :param pulumi.Input[_builtins.str] ssh_ca_id: The ID of the SSH Certificate Authority used for SSH access.
        :param pulumi.Input[_builtins.str] x509_ca_id: The ID of the X.509 Certificate Authority used for TLS.
        """
        if address is not None:
            pulumi.set(__self__, "address", address)
        if remote_network_id is not None:
            pulumi.set(__self__, "remote_network_id", remote_network_id)
        if ssh_ca_id is not None:
            pulumi.set(__self__, "ssh_ca_id", ssh_ca_id)
        if x509_ca_id is not None:
            pulumi.set(__self__, "x509_ca_id", x509_ca_id)

    @_builtins.property
    @pulumi.getter
    def address(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The address of the Gateway.
        """
        return pulumi.get(self, "address")

    @address.setter
    def address(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "address", value)

    @_builtins.property
    @pulumi.getter(name="remoteNetworkId")
    def remote_network_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the Remote Network the Gateway belongs to.
        """
        return pulumi.get(self, "remote_network_id")

    @remote_network_id.setter
    def remote_network_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "remote_network_id", value)

    @_builtins.property
    @pulumi.getter(name="sshCaId")
    def ssh_ca_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the SSH Certificate Authority used for SSH access.
        """
        return pulumi.get(self, "ssh_ca_id")

    @ssh_ca_id.setter
    def ssh_ca_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ssh_ca_id", value)

    @_builtins.property
    @pulumi.getter(name="x509CaId")
    def x509_ca_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the X.509 Certificate Authority used for TLS.
        """
        return pulumi.get(self, "x509_ca_id")

    @x509_ca_id.setter
    def x509_ca_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "x509_ca_id", value)


@pulumi.type_token("twingate:index/twingateGateway:TwingateGateway")
class TwingateGateway(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 address: Optional[pulumi.Input[_builtins.str]] = None,
                 remote_network_id: Optional[pulumi.Input[_builtins.str]] = None,
                 ssh_ca_id: Optional[pulumi.Input[_builtins.str]] = None,
                 x509_ca_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Gateways are the Twingate components that route traffic to remote networks.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_std as std
        import pulumi_twingate as twingate

        gcp = twingate.TwingateRemoteNetwork("gcp", name="GCP Network")
        tls = twingate.TwingateX509CertificateAuthority("tls",
            name="My TLS CA",
            certificate=std.file(input="ca.pem").result)
        ssh = twingate.TwingateSSHCertificateAuthority("ssh",
            name="My SSH CA",
            public_key=std.trimspace(input=std.file(input="~/.ssh/id_ed25519.pub").result).result)
        # Gateway with both X.509 and SSH CAs
        main = twingate.TwingateGateway("main",
            remote_network_id=gcp.id,
            address="10.0.0.1:8443",
            x509_ca_id=tls.id,
            ssh_ca_id=ssh.id)
        # Gateway with only X.509 CA (ssh_ca_id is optional)
        minimal = twingate.TwingateGateway("minimal",
            remote_network_id=gcp.id,
            address="10.0.0.2:9001",
            x509_ca_id=tls.id)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] address: The address of the Gateway.
        :param pulumi.Input[_builtins.str] remote_network_id: The ID of the Remote Network the Gateway belongs to.
        :param pulumi.Input[_builtins.str] ssh_ca_id: The ID of the SSH Certificate Authority used for SSH access.
        :param pulumi.Input[_builtins.str] x509_ca_id: The ID of the X.509 Certificate Authority used for TLS.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: TwingateGatewayArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Gateways are the Twingate components that route traffic to remote networks.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_std as std
        import pulumi_twingate as twingate

        gcp = twingate.TwingateRemoteNetwork("gcp", name="GCP Network")
        tls = twingate.TwingateX509CertificateAuthority("tls",
            name="My TLS CA",
            certificate=std.file(input="ca.pem").result)
        ssh = twingate.TwingateSSHCertificateAuthority("ssh",
            name="My SSH CA",
            public_key=std.trimspace(input=std.file(input="~/.ssh/id_ed25519.pub").result).result)
        # Gateway with both X.509 and SSH CAs
        main = twingate.TwingateGateway("main",
            remote_network_id=gcp.id,
            address="10.0.0.1:8443",
            x509_ca_id=tls.id,
            ssh_ca_id=ssh.id)
        # Gateway with only X.509 CA (ssh_ca_id is optional)
        minimal = twingate.TwingateGateway("minimal",
            remote_network_id=gcp.id,
            address="10.0.0.2:9001",
            x509_ca_id=tls.id)
        ```


        :param str resource_name: The name of the resource.
        :param TwingateGatewayArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TwingateGatewayArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 address: Optional[pulumi.Input[_builtins.str]] = None,
                 remote_network_id: Optional[pulumi.Input[_builtins.str]] = None,
                 ssh_ca_id: Optional[pulumi.Input[_builtins.str]] = None,
                 x509_ca_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TwingateGatewayArgs.__new__(TwingateGatewayArgs)

            if address is None and not opts.urn:
                raise TypeError("Missing required property 'address'")
            __props__.__dict__["address"] = address
            if remote_network_id is None and not opts.urn:
                raise TypeError("Missing required property 'remote_network_id'")
            __props__.__dict__["remote_network_id"] = remote_network_id
            __props__.__dict__["ssh_ca_id"] = ssh_ca_id
            if x509_ca_id is None and not opts.urn:
                raise TypeError("Missing required property 'x509_ca_id'")
            __props__.__dict__["x509_ca_id"] = x509_ca_id
        super(TwingateGateway, __self__).__init__(
            'twingate:index/twingateGateway:TwingateGateway',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            address: Optional[pulumi.Input[_builtins.str]] = None,
            remote_network_id: Optional[pulumi.Input[_builtins.str]] = None,
            ssh_ca_id: Optional[pulumi.Input[_builtins.str]] = None,
            x509_ca_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'TwingateGateway':
        """
        Get an existing TwingateGateway resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] address: The address of the Gateway.
        :param pulumi.Input[_builtins.str] remote_network_id: The ID of the Remote Network the Gateway belongs to.
        :param pulumi.Input[_builtins.str] ssh_ca_id: The ID of the SSH Certificate Authority used for SSH access.
        :param pulumi.Input[_builtins.str] x509_ca_id: The ID of the X.509 Certificate Authority used for TLS.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _TwingateGatewayState.__new__(_TwingateGatewayState)

        __props__.__dict__["address"] = address
        __props__.__dict__["remote_network_id"] = remote_network_id
        __props__.__dict__["ssh_ca_id"] = ssh_ca_id
        __props__.__dict__["x509_ca_id"] = x509_ca_id
        return TwingateGateway(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def address(self) -> pulumi.Output[_builtins.str]:
        """
        The address of the Gateway.
        """
        return pulumi.get(self, "address")

    @_builtins.property
    @pulumi.getter(name="remoteNetworkId")
    def remote_network_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the Remote Network the Gateway belongs to.
        """
        return pulumi.get(self, "remote_network_id")

    @_builtins.property
    @pulumi.getter(name="sshCaId")
    def ssh_ca_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The ID of the SSH Certificate Authority used for SSH access.
        """
        return pulumi.get(self, "ssh_ca_id")

    @_builtins.property
    @pulumi.getter(name="x509CaId")
    def x509_ca_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the X.509 Certificate Authority used for TLS.
        """
        return pulumi.get(self, "x509_ca_id")

