# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['TwingateKubernetesResourceArgs', 'TwingateKubernetesResource']

@pulumi.input_type
class TwingateKubernetesResourceArgs:
    def __init__(__self__, *,
                 gateway_id: pulumi.Input[_builtins.str],
                 remote_network_id: pulumi.Input[_builtins.str],
                 access_groups: Optional[pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessGroupArgs']]]] = None,
                 access_policies: Optional[pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessPolicyArgs']]]] = None,
                 address: Optional[pulumi.Input[_builtins.str]] = None,
                 alias: Optional[pulumi.Input[_builtins.str]] = None,
                 bearer_token_file: Optional[pulumi.Input[_builtins.str]] = None,
                 ca_file: Optional[pulumi.Input[_builtins.str]] = None,
                 in_cluster: Optional[pulumi.Input[_builtins.bool]] = None,
                 is_visible: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 protocols: Optional[pulumi.Input['TwingateKubernetesResourceProtocolsArgs']] = None,
                 security_policy_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a TwingateKubernetesResource resource.

        :param pulumi.Input[_builtins.str] gateway_id: The ID of the Gateway used to access this Kubernetes Resource.
        :param pulumi.Input[_builtins.str] remote_network_id: The ID of the Remote Network the Kubernetes Resource belongs to.
        :param pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessGroupArgs']]] access_groups: Restrict access to certain group
        :param pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessPolicyArgs']]] access_policies: Restrict access according to JIT access policy
        :param pulumi.Input[_builtins.str] address: The address of the Kubernetes Resource (IP or FQDN).
        :param pulumi.Input[_builtins.str] alias: Set a DNS alias address for the Resource. Must be a DNS-valid name string.
        :param pulumi.Input[_builtins.str] bearer_token_file: Path to bearer token file.
        :param pulumi.Input[_builtins.str] ca_file: Path to CA certificate file.
        :param pulumi.Input[_builtins.bool] in_cluster: Whether the Gateway is running inside the same Kubernetes cluster that is represented by the Kubernetes Resource. Default is `true`.
        :param pulumi.Input[_builtins.bool] is_visible: Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `true`.
        :param pulumi.Input[_builtins.str] name: The name of the Kubernetes Resource.
        :param pulumi.Input['TwingateKubernetesResourceProtocolsArgs'] protocols: Restrict access to certain protocols and ports. By default or when this argument is not defined, there is no restriction, and all protocols and ports are allowed.
        :param pulumi.Input[_builtins.str] security_policy_id: The ID of a `get_twingate_security_policy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: A map of key-value pair tags to set on this resource.
        """
        pulumi.set(__self__, "gateway_id", gateway_id)
        pulumi.set(__self__, "remote_network_id", remote_network_id)
        if access_groups is not None:
            pulumi.set(__self__, "access_groups", access_groups)
        if access_policies is not None:
            pulumi.set(__self__, "access_policies", access_policies)
        if address is not None:
            pulumi.set(__self__, "address", address)
        if alias is not None:
            pulumi.set(__self__, "alias", alias)
        if bearer_token_file is not None:
            pulumi.set(__self__, "bearer_token_file", bearer_token_file)
        if ca_file is not None:
            pulumi.set(__self__, "ca_file", ca_file)
        if in_cluster is not None:
            pulumi.set(__self__, "in_cluster", in_cluster)
        if is_visible is not None:
            pulumi.set(__self__, "is_visible", is_visible)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if protocols is not None:
            pulumi.set(__self__, "protocols", protocols)
        if security_policy_id is not None:
            pulumi.set(__self__, "security_policy_id", security_policy_id)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter(name="gatewayId")
    def gateway_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the Gateway used to access this Kubernetes Resource.
        """
        return pulumi.get(self, "gateway_id")

    @gateway_id.setter
    def gateway_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "gateway_id", value)

    @_builtins.property
    @pulumi.getter(name="remoteNetworkId")
    def remote_network_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the Remote Network the Kubernetes Resource belongs to.
        """
        return pulumi.get(self, "remote_network_id")

    @remote_network_id.setter
    def remote_network_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "remote_network_id", value)

    @_builtins.property
    @pulumi.getter(name="accessGroups")
    def access_groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessGroupArgs']]]]:
        """
        Restrict access to certain group
        """
        return pulumi.get(self, "access_groups")

    @access_groups.setter
    def access_groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessGroupArgs']]]]):
        pulumi.set(self, "access_groups", value)

    @_builtins.property
    @pulumi.getter(name="accessPolicies")
    def access_policies(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessPolicyArgs']]]]:
        """
        Restrict access according to JIT access policy
        """
        return pulumi.get(self, "access_policies")

    @access_policies.setter
    def access_policies(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessPolicyArgs']]]]):
        pulumi.set(self, "access_policies", value)

    @_builtins.property
    @pulumi.getter
    def address(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The address of the Kubernetes Resource (IP or FQDN).
        """
        return pulumi.get(self, "address")

    @address.setter
    def address(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "address", value)

    @_builtins.property
    @pulumi.getter
    def alias(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Set a DNS alias address for the Resource. Must be a DNS-valid name string.
        """
        return pulumi.get(self, "alias")

    @alias.setter
    def alias(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "alias", value)

    @_builtins.property
    @pulumi.getter(name="bearerTokenFile")
    def bearer_token_file(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Path to bearer token file.
        """
        return pulumi.get(self, "bearer_token_file")

    @bearer_token_file.setter
    def bearer_token_file(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "bearer_token_file", value)

    @_builtins.property
    @pulumi.getter(name="caFile")
    def ca_file(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Path to CA certificate file.
        """
        return pulumi.get(self, "ca_file")

    @ca_file.setter
    def ca_file(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ca_file", value)

    @_builtins.property
    @pulumi.getter(name="inCluster")
    def in_cluster(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the Gateway is running inside the same Kubernetes cluster that is represented by the Kubernetes Resource. Default is `true`.
        """
        return pulumi.get(self, "in_cluster")

    @in_cluster.setter
    def in_cluster(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "in_cluster", value)

    @_builtins.property
    @pulumi.getter(name="isVisible")
    def is_visible(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `true`.
        """
        return pulumi.get(self, "is_visible")

    @is_visible.setter
    def is_visible(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_visible", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the Kubernetes Resource.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def protocols(self) -> Optional[pulumi.Input['TwingateKubernetesResourceProtocolsArgs']]:
        """
        Restrict access to certain protocols and ports. By default or when this argument is not defined, there is no restriction, and all protocols and ports are allowed.
        """
        return pulumi.get(self, "protocols")

    @protocols.setter
    def protocols(self, value: Optional[pulumi.Input['TwingateKubernetesResourceProtocolsArgs']]):
        pulumi.set(self, "protocols", value)

    @_builtins.property
    @pulumi.getter(name="securityPolicyId")
    def security_policy_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of a `get_twingate_security_policy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.
        """
        return pulumi.get(self, "security_policy_id")

    @security_policy_id.setter
    def security_policy_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "security_policy_id", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        A map of key-value pair tags to set on this resource.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)


@pulumi.input_type
class _TwingateKubernetesResourceState:
    def __init__(__self__, *,
                 access_groups: Optional[pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessGroupArgs']]]] = None,
                 access_policies: Optional[pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessPolicyArgs']]]] = None,
                 address: Optional[pulumi.Input[_builtins.str]] = None,
                 alias: Optional[pulumi.Input[_builtins.str]] = None,
                 bearer_token_file: Optional[pulumi.Input[_builtins.str]] = None,
                 ca_file: Optional[pulumi.Input[_builtins.str]] = None,
                 gateway_id: Optional[pulumi.Input[_builtins.str]] = None,
                 in_cluster: Optional[pulumi.Input[_builtins.bool]] = None,
                 is_visible: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 protocols: Optional[pulumi.Input['TwingateKubernetesResourceProtocolsArgs']] = None,
                 remote_network_id: Optional[pulumi.Input[_builtins.str]] = None,
                 security_policy_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering TwingateKubernetesResource resources.

        :param pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessGroupArgs']]] access_groups: Restrict access to certain group
        :param pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessPolicyArgs']]] access_policies: Restrict access according to JIT access policy
        :param pulumi.Input[_builtins.str] address: The address of the Kubernetes Resource (IP or FQDN).
        :param pulumi.Input[_builtins.str] alias: Set a DNS alias address for the Resource. Must be a DNS-valid name string.
        :param pulumi.Input[_builtins.str] bearer_token_file: Path to bearer token file.
        :param pulumi.Input[_builtins.str] ca_file: Path to CA certificate file.
        :param pulumi.Input[_builtins.str] gateway_id: The ID of the Gateway used to access this Kubernetes Resource.
        :param pulumi.Input[_builtins.bool] in_cluster: Whether the Gateway is running inside the same Kubernetes cluster that is represented by the Kubernetes Resource. Default is `true`.
        :param pulumi.Input[_builtins.bool] is_visible: Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `true`.
        :param pulumi.Input[_builtins.str] name: The name of the Kubernetes Resource.
        :param pulumi.Input['TwingateKubernetesResourceProtocolsArgs'] protocols: Restrict access to certain protocols and ports. By default or when this argument is not defined, there is no restriction, and all protocols and ports are allowed.
        :param pulumi.Input[_builtins.str] remote_network_id: The ID of the Remote Network the Kubernetes Resource belongs to.
        :param pulumi.Input[_builtins.str] security_policy_id: The ID of a `get_twingate_security_policy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: A map of key-value pair tags to set on this resource.
        """
        if access_groups is not None:
            pulumi.set(__self__, "access_groups", access_groups)
        if access_policies is not None:
            pulumi.set(__self__, "access_policies", access_policies)
        if address is not None:
            pulumi.set(__self__, "address", address)
        if alias is not None:
            pulumi.set(__self__, "alias", alias)
        if bearer_token_file is not None:
            pulumi.set(__self__, "bearer_token_file", bearer_token_file)
        if ca_file is not None:
            pulumi.set(__self__, "ca_file", ca_file)
        if gateway_id is not None:
            pulumi.set(__self__, "gateway_id", gateway_id)
        if in_cluster is not None:
            pulumi.set(__self__, "in_cluster", in_cluster)
        if is_visible is not None:
            pulumi.set(__self__, "is_visible", is_visible)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if protocols is not None:
            pulumi.set(__self__, "protocols", protocols)
        if remote_network_id is not None:
            pulumi.set(__self__, "remote_network_id", remote_network_id)
        if security_policy_id is not None:
            pulumi.set(__self__, "security_policy_id", security_policy_id)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter(name="accessGroups")
    def access_groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessGroupArgs']]]]:
        """
        Restrict access to certain group
        """
        return pulumi.get(self, "access_groups")

    @access_groups.setter
    def access_groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessGroupArgs']]]]):
        pulumi.set(self, "access_groups", value)

    @_builtins.property
    @pulumi.getter(name="accessPolicies")
    def access_policies(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessPolicyArgs']]]]:
        """
        Restrict access according to JIT access policy
        """
        return pulumi.get(self, "access_policies")

    @access_policies.setter
    def access_policies(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['TwingateKubernetesResourceAccessPolicyArgs']]]]):
        pulumi.set(self, "access_policies", value)

    @_builtins.property
    @pulumi.getter
    def address(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The address of the Kubernetes Resource (IP or FQDN).
        """
        return pulumi.get(self, "address")

    @address.setter
    def address(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "address", value)

    @_builtins.property
    @pulumi.getter
    def alias(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Set a DNS alias address for the Resource. Must be a DNS-valid name string.
        """
        return pulumi.get(self, "alias")

    @alias.setter
    def alias(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "alias", value)

    @_builtins.property
    @pulumi.getter(name="bearerTokenFile")
    def bearer_token_file(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Path to bearer token file.
        """
        return pulumi.get(self, "bearer_token_file")

    @bearer_token_file.setter
    def bearer_token_file(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "bearer_token_file", value)

    @_builtins.property
    @pulumi.getter(name="caFile")
    def ca_file(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Path to CA certificate file.
        """
        return pulumi.get(self, "ca_file")

    @ca_file.setter
    def ca_file(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ca_file", value)

    @_builtins.property
    @pulumi.getter(name="gatewayId")
    def gateway_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the Gateway used to access this Kubernetes Resource.
        """
        return pulumi.get(self, "gateway_id")

    @gateway_id.setter
    def gateway_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "gateway_id", value)

    @_builtins.property
    @pulumi.getter(name="inCluster")
    def in_cluster(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the Gateway is running inside the same Kubernetes cluster that is represented by the Kubernetes Resource. Default is `true`.
        """
        return pulumi.get(self, "in_cluster")

    @in_cluster.setter
    def in_cluster(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "in_cluster", value)

    @_builtins.property
    @pulumi.getter(name="isVisible")
    def is_visible(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `true`.
        """
        return pulumi.get(self, "is_visible")

    @is_visible.setter
    def is_visible(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_visible", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the Kubernetes Resource.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def protocols(self) -> Optional[pulumi.Input['TwingateKubernetesResourceProtocolsArgs']]:
        """
        Restrict access to certain protocols and ports. By default or when this argument is not defined, there is no restriction, and all protocols and ports are allowed.
        """
        return pulumi.get(self, "protocols")

    @protocols.setter
    def protocols(self, value: Optional[pulumi.Input['TwingateKubernetesResourceProtocolsArgs']]):
        pulumi.set(self, "protocols", value)

    @_builtins.property
    @pulumi.getter(name="remoteNetworkId")
    def remote_network_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the Remote Network the Kubernetes Resource belongs to.
        """
        return pulumi.get(self, "remote_network_id")

    @remote_network_id.setter
    def remote_network_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "remote_network_id", value)

    @_builtins.property
    @pulumi.getter(name="securityPolicyId")
    def security_policy_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of a `get_twingate_security_policy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.
        """
        return pulumi.get(self, "security_policy_id")

    @security_policy_id.setter
    def security_policy_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "security_policy_id", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        A map of key-value pair tags to set on this resource.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)


@pulumi.type_token("twingate:index/twingateKubernetesResource:TwingateKubernetesResource")
class TwingateKubernetesResource(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_groups: Optional[pulumi.Input[Sequence[pulumi.Input[Union['TwingateKubernetesResourceAccessGroupArgs', 'TwingateKubernetesResourceAccessGroupArgsDict']]]]] = None,
                 access_policies: Optional[pulumi.Input[Sequence[pulumi.Input[Union['TwingateKubernetesResourceAccessPolicyArgs', 'TwingateKubernetesResourceAccessPolicyArgsDict']]]]] = None,
                 address: Optional[pulumi.Input[_builtins.str]] = None,
                 alias: Optional[pulumi.Input[_builtins.str]] = None,
                 bearer_token_file: Optional[pulumi.Input[_builtins.str]] = None,
                 ca_file: Optional[pulumi.Input[_builtins.str]] = None,
                 gateway_id: Optional[pulumi.Input[_builtins.str]] = None,
                 in_cluster: Optional[pulumi.Input[_builtins.bool]] = None,
                 is_visible: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 protocols: Optional[pulumi.Input[Union['TwingateKubernetesResourceProtocolsArgs', 'TwingateKubernetesResourceProtocolsArgsDict']]] = None,
                 remote_network_id: Optional[pulumi.Input[_builtins.str]] = None,
                 security_policy_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Kubernetes Resources are Twingate resources accessed via a Gateway.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_std as std
        import pulumi_twingate as twingate

        prod = twingate.TwingateRemoteNetwork("prod", name="Production Network")
        tls = twingate.TwingateX509CertificateAuthority("tls",
            name="My TLS CA",
            certificate=std.file(input="ca.pem").result)
        main = twingate.TwingateGateway("main",
            remote_network_id=prod.id,
            address="10.0.0.1:8443",
            x509_ca_id=tls.id)
        # Kubernetes resource accessed via in-cluster DNS
        prod_cluster = twingate.TwingateKubernetesResource("prod_cluster",
            name="Production K8s",
            gateway_id=main.id,
            remote_network_id=prod.id)
        # Kubernetes resource accessed via external address
        external_cluster = twingate.TwingateKubernetesResource("external_cluster",
            name="External K8s",
            address="k8s-api.example.com",
            gateway_id=main.id,
            remote_network_id=prod.id)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['TwingateKubernetesResourceAccessGroupArgs', 'TwingateKubernetesResourceAccessGroupArgsDict']]]] access_groups: Restrict access to certain group
        :param pulumi.Input[Sequence[pulumi.Input[Union['TwingateKubernetesResourceAccessPolicyArgs', 'TwingateKubernetesResourceAccessPolicyArgsDict']]]] access_policies: Restrict access according to JIT access policy
        :param pulumi.Input[_builtins.str] address: The address of the Kubernetes Resource (IP or FQDN).
        :param pulumi.Input[_builtins.str] alias: Set a DNS alias address for the Resource. Must be a DNS-valid name string.
        :param pulumi.Input[_builtins.str] bearer_token_file: Path to bearer token file.
        :param pulumi.Input[_builtins.str] ca_file: Path to CA certificate file.
        :param pulumi.Input[_builtins.str] gateway_id: The ID of the Gateway used to access this Kubernetes Resource.
        :param pulumi.Input[_builtins.bool] in_cluster: Whether the Gateway is running inside the same Kubernetes cluster that is represented by the Kubernetes Resource. Default is `true`.
        :param pulumi.Input[_builtins.bool] is_visible: Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `true`.
        :param pulumi.Input[_builtins.str] name: The name of the Kubernetes Resource.
        :param pulumi.Input[Union['TwingateKubernetesResourceProtocolsArgs', 'TwingateKubernetesResourceProtocolsArgsDict']] protocols: Restrict access to certain protocols and ports. By default or when this argument is not defined, there is no restriction, and all protocols and ports are allowed.
        :param pulumi.Input[_builtins.str] remote_network_id: The ID of the Remote Network the Kubernetes Resource belongs to.
        :param pulumi.Input[_builtins.str] security_policy_id: The ID of a `get_twingate_security_policy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: A map of key-value pair tags to set on this resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: TwingateKubernetesResourceArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Kubernetes Resources are Twingate resources accessed via a Gateway.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_std as std
        import pulumi_twingate as twingate

        prod = twingate.TwingateRemoteNetwork("prod", name="Production Network")
        tls = twingate.TwingateX509CertificateAuthority("tls",
            name="My TLS CA",
            certificate=std.file(input="ca.pem").result)
        main = twingate.TwingateGateway("main",
            remote_network_id=prod.id,
            address="10.0.0.1:8443",
            x509_ca_id=tls.id)
        # Kubernetes resource accessed via in-cluster DNS
        prod_cluster = twingate.TwingateKubernetesResource("prod_cluster",
            name="Production K8s",
            gateway_id=main.id,
            remote_network_id=prod.id)
        # Kubernetes resource accessed via external address
        external_cluster = twingate.TwingateKubernetesResource("external_cluster",
            name="External K8s",
            address="k8s-api.example.com",
            gateway_id=main.id,
            remote_network_id=prod.id)
        ```


        :param str resource_name: The name of the resource.
        :param TwingateKubernetesResourceArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TwingateKubernetesResourceArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_groups: Optional[pulumi.Input[Sequence[pulumi.Input[Union['TwingateKubernetesResourceAccessGroupArgs', 'TwingateKubernetesResourceAccessGroupArgsDict']]]]] = None,
                 access_policies: Optional[pulumi.Input[Sequence[pulumi.Input[Union['TwingateKubernetesResourceAccessPolicyArgs', 'TwingateKubernetesResourceAccessPolicyArgsDict']]]]] = None,
                 address: Optional[pulumi.Input[_builtins.str]] = None,
                 alias: Optional[pulumi.Input[_builtins.str]] = None,
                 bearer_token_file: Optional[pulumi.Input[_builtins.str]] = None,
                 ca_file: Optional[pulumi.Input[_builtins.str]] = None,
                 gateway_id: Optional[pulumi.Input[_builtins.str]] = None,
                 in_cluster: Optional[pulumi.Input[_builtins.bool]] = None,
                 is_visible: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 protocols: Optional[pulumi.Input[Union['TwingateKubernetesResourceProtocolsArgs', 'TwingateKubernetesResourceProtocolsArgsDict']]] = None,
                 remote_network_id: Optional[pulumi.Input[_builtins.str]] = None,
                 security_policy_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TwingateKubernetesResourceArgs.__new__(TwingateKubernetesResourceArgs)

            __props__.__dict__["access_groups"] = access_groups
            __props__.__dict__["access_policies"] = access_policies
            __props__.__dict__["address"] = address
            __props__.__dict__["alias"] = alias
            __props__.__dict__["bearer_token_file"] = bearer_token_file
            __props__.__dict__["ca_file"] = ca_file
            if gateway_id is None and not opts.urn:
                raise TypeError("Missing required property 'gateway_id'")
            __props__.__dict__["gateway_id"] = gateway_id
            __props__.__dict__["in_cluster"] = in_cluster
            __props__.__dict__["is_visible"] = is_visible
            __props__.__dict__["name"] = name
            __props__.__dict__["protocols"] = protocols
            if remote_network_id is None and not opts.urn:
                raise TypeError("Missing required property 'remote_network_id'")
            __props__.__dict__["remote_network_id"] = remote_network_id
            __props__.__dict__["security_policy_id"] = security_policy_id
            __props__.__dict__["tags"] = tags
        super(TwingateKubernetesResource, __self__).__init__(
            'twingate:index/twingateKubernetesResource:TwingateKubernetesResource',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            access_groups: Optional[pulumi.Input[Sequence[pulumi.Input[Union['TwingateKubernetesResourceAccessGroupArgs', 'TwingateKubernetesResourceAccessGroupArgsDict']]]]] = None,
            access_policies: Optional[pulumi.Input[Sequence[pulumi.Input[Union['TwingateKubernetesResourceAccessPolicyArgs', 'TwingateKubernetesResourceAccessPolicyArgsDict']]]]] = None,
            address: Optional[pulumi.Input[_builtins.str]] = None,
            alias: Optional[pulumi.Input[_builtins.str]] = None,
            bearer_token_file: Optional[pulumi.Input[_builtins.str]] = None,
            ca_file: Optional[pulumi.Input[_builtins.str]] = None,
            gateway_id: Optional[pulumi.Input[_builtins.str]] = None,
            in_cluster: Optional[pulumi.Input[_builtins.bool]] = None,
            is_visible: Optional[pulumi.Input[_builtins.bool]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            protocols: Optional[pulumi.Input[Union['TwingateKubernetesResourceProtocolsArgs', 'TwingateKubernetesResourceProtocolsArgsDict']]] = None,
            remote_network_id: Optional[pulumi.Input[_builtins.str]] = None,
            security_policy_id: Optional[pulumi.Input[_builtins.str]] = None,
            tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None) -> 'TwingateKubernetesResource':
        """
        Get an existing TwingateKubernetesResource resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['TwingateKubernetesResourceAccessGroupArgs', 'TwingateKubernetesResourceAccessGroupArgsDict']]]] access_groups: Restrict access to certain group
        :param pulumi.Input[Sequence[pulumi.Input[Union['TwingateKubernetesResourceAccessPolicyArgs', 'TwingateKubernetesResourceAccessPolicyArgsDict']]]] access_policies: Restrict access according to JIT access policy
        :param pulumi.Input[_builtins.str] address: The address of the Kubernetes Resource (IP or FQDN).
        :param pulumi.Input[_builtins.str] alias: Set a DNS alias address for the Resource. Must be a DNS-valid name string.
        :param pulumi.Input[_builtins.str] bearer_token_file: Path to bearer token file.
        :param pulumi.Input[_builtins.str] ca_file: Path to CA certificate file.
        :param pulumi.Input[_builtins.str] gateway_id: The ID of the Gateway used to access this Kubernetes Resource.
        :param pulumi.Input[_builtins.bool] in_cluster: Whether the Gateway is running inside the same Kubernetes cluster that is represented by the Kubernetes Resource. Default is `true`.
        :param pulumi.Input[_builtins.bool] is_visible: Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `true`.
        :param pulumi.Input[_builtins.str] name: The name of the Kubernetes Resource.
        :param pulumi.Input[Union['TwingateKubernetesResourceProtocolsArgs', 'TwingateKubernetesResourceProtocolsArgsDict']] protocols: Restrict access to certain protocols and ports. By default or when this argument is not defined, there is no restriction, and all protocols and ports are allowed.
        :param pulumi.Input[_builtins.str] remote_network_id: The ID of the Remote Network the Kubernetes Resource belongs to.
        :param pulumi.Input[_builtins.str] security_policy_id: The ID of a `get_twingate_security_policy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: A map of key-value pair tags to set on this resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _TwingateKubernetesResourceState.__new__(_TwingateKubernetesResourceState)

        __props__.__dict__["access_groups"] = access_groups
        __props__.__dict__["access_policies"] = access_policies
        __props__.__dict__["address"] = address
        __props__.__dict__["alias"] = alias
        __props__.__dict__["bearer_token_file"] = bearer_token_file
        __props__.__dict__["ca_file"] = ca_file
        __props__.__dict__["gateway_id"] = gateway_id
        __props__.__dict__["in_cluster"] = in_cluster
        __props__.__dict__["is_visible"] = is_visible
        __props__.__dict__["name"] = name
        __props__.__dict__["protocols"] = protocols
        __props__.__dict__["remote_network_id"] = remote_network_id
        __props__.__dict__["security_policy_id"] = security_policy_id
        __props__.__dict__["tags"] = tags
        return TwingateKubernetesResource(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accessGroups")
    def access_groups(self) -> pulumi.Output[Optional[Sequence['outputs.TwingateKubernetesResourceAccessGroup']]]:
        """
        Restrict access to certain group
        """
        return pulumi.get(self, "access_groups")

    @_builtins.property
    @pulumi.getter(name="accessPolicies")
    def access_policies(self) -> pulumi.Output[Optional[Sequence['outputs.TwingateKubernetesResourceAccessPolicy']]]:
        """
        Restrict access according to JIT access policy
        """
        return pulumi.get(self, "access_policies")

    @_builtins.property
    @pulumi.getter
    def address(self) -> pulumi.Output[_builtins.str]:
        """
        The address of the Kubernetes Resource (IP or FQDN).
        """
        return pulumi.get(self, "address")

    @_builtins.property
    @pulumi.getter
    def alias(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Set a DNS alias address for the Resource. Must be a DNS-valid name string.
        """
        return pulumi.get(self, "alias")

    @_builtins.property
    @pulumi.getter(name="bearerTokenFile")
    def bearer_token_file(self) -> pulumi.Output[_builtins.str]:
        """
        Path to bearer token file.
        """
        return pulumi.get(self, "bearer_token_file")

    @_builtins.property
    @pulumi.getter(name="caFile")
    def ca_file(self) -> pulumi.Output[_builtins.str]:
        """
        Path to CA certificate file.
        """
        return pulumi.get(self, "ca_file")

    @_builtins.property
    @pulumi.getter(name="gatewayId")
    def gateway_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the Gateway used to access this Kubernetes Resource.
        """
        return pulumi.get(self, "gateway_id")

    @_builtins.property
    @pulumi.getter(name="inCluster")
    def in_cluster(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the Gateway is running inside the same Kubernetes cluster that is represented by the Kubernetes Resource. Default is `true`.
        """
        return pulumi.get(self, "in_cluster")

    @_builtins.property
    @pulumi.getter(name="isVisible")
    def is_visible(self) -> pulumi.Output[_builtins.bool]:
        """
        Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `true`.
        """
        return pulumi.get(self, "is_visible")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the Kubernetes Resource.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def protocols(self) -> pulumi.Output['outputs.TwingateKubernetesResourceProtocols']:
        """
        Restrict access to certain protocols and ports. By default or when this argument is not defined, there is no restriction, and all protocols and ports are allowed.
        """
        return pulumi.get(self, "protocols")

    @_builtins.property
    @pulumi.getter(name="remoteNetworkId")
    def remote_network_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the Remote Network the Kubernetes Resource belongs to.
        """
        return pulumi.get(self, "remote_network_id")

    @_builtins.property
    @pulumi.getter(name="securityPolicyId")
    def security_policy_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of a `get_twingate_security_policy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.
        """
        return pulumi.get(self, "security_policy_id")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        A map of key-value pair tags to set on this resource.
        """
        return pulumi.get(self, "tags")

