// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"context"
	"reflect"

	"github.com/Twingate/pulumi-twingate/sdk/v3/go/twingate/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type Cache struct {
	// Specifies whether the provider should cache groups. The default value is `true`.
	GroupsEnabled *bool `pulumi:"groupsEnabled"`
	// Specifies whether the provider should cache resources. The default value is `true`.
	ResourceEnabled *bool `pulumi:"resourceEnabled"`
}

// CacheInput is an input type that accepts CacheArgs and CacheOutput values.
// You can construct a concrete instance of `CacheInput` via:
//
//	CacheArgs{...}
type CacheInput interface {
	pulumi.Input

	ToCacheOutput() CacheOutput
	ToCacheOutputWithContext(context.Context) CacheOutput
}

type CacheArgs struct {
	// Specifies whether the provider should cache groups. The default value is `true`.
	GroupsEnabled pulumi.BoolPtrInput `pulumi:"groupsEnabled"`
	// Specifies whether the provider should cache resources. The default value is `true`.
	ResourceEnabled pulumi.BoolPtrInput `pulumi:"resourceEnabled"`
}

func (CacheArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Cache)(nil)).Elem()
}

func (i CacheArgs) ToCacheOutput() CacheOutput {
	return i.ToCacheOutputWithContext(context.Background())
}

func (i CacheArgs) ToCacheOutputWithContext(ctx context.Context) CacheOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CacheOutput)
}

type CacheOutput struct{ *pulumi.OutputState }

func (CacheOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Cache)(nil)).Elem()
}

func (o CacheOutput) ToCacheOutput() CacheOutput {
	return o
}

func (o CacheOutput) ToCacheOutputWithContext(ctx context.Context) CacheOutput {
	return o
}

// Specifies whether the provider should cache groups. The default value is `true`.
func (o CacheOutput) GroupsEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v Cache) *bool { return v.GroupsEnabled }).(pulumi.BoolPtrOutput)
}

// Specifies whether the provider should cache resources. The default value is `true`.
func (o CacheOutput) ResourceEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v Cache) *bool { return v.ResourceEnabled }).(pulumi.BoolPtrOutput)
}

type DefaultTags struct {
	// A map of key-value pair tags to be set on all resources by default.
	Tags map[string]string `pulumi:"tags"`
}

// DefaultTagsInput is an input type that accepts DefaultTagsArgs and DefaultTagsOutput values.
// You can construct a concrete instance of `DefaultTagsInput` via:
//
//	DefaultTagsArgs{...}
type DefaultTagsInput interface {
	pulumi.Input

	ToDefaultTagsOutput() DefaultTagsOutput
	ToDefaultTagsOutputWithContext(context.Context) DefaultTagsOutput
}

type DefaultTagsArgs struct {
	// A map of key-value pair tags to be set on all resources by default.
	Tags pulumi.StringMapInput `pulumi:"tags"`
}

func (DefaultTagsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DefaultTags)(nil)).Elem()
}

func (i DefaultTagsArgs) ToDefaultTagsOutput() DefaultTagsOutput {
	return i.ToDefaultTagsOutputWithContext(context.Background())
}

func (i DefaultTagsArgs) ToDefaultTagsOutputWithContext(ctx context.Context) DefaultTagsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultTagsOutput)
}

type DefaultTagsOutput struct{ *pulumi.OutputState }

func (DefaultTagsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DefaultTags)(nil)).Elem()
}

func (o DefaultTagsOutput) ToDefaultTagsOutput() DefaultTagsOutput {
	return o
}

func (o DefaultTagsOutput) ToDefaultTagsOutputWithContext(ctx context.Context) DefaultTagsOutput {
	return o
}

// A map of key-value pair tags to be set on all resources by default.
func (o DefaultTagsOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v DefaultTags) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CacheInput)(nil)).Elem(), CacheArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultTagsInput)(nil)).Elem(), DefaultTagsArgs{})
	pulumi.RegisterOutputType(CacheOutput{})
	pulumi.RegisterOutputType(DefaultTagsOutput{})
}
