// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate.Outputs
{

    [OutputType]
    public sealed class GetTwingateDNSFilteringProfilePrivacyCategoriesResult
    {
        /// <summary>
        /// Whether to block ads and trackers.
        /// </summary>
        public readonly bool BlockAdsAndTrackers;
        /// <summary>
        /// Whether to block affiliate links.
        /// </summary>
        public readonly bool BlockAffiliateLinks;
        /// <summary>
        /// Whether to block disguised third party trackers.
        /// </summary>
        public readonly bool BlockDisguisedTrackers;

        [OutputConstructor]
        private GetTwingateDNSFilteringProfilePrivacyCategoriesResult(
            bool blockAdsAndTrackers,

            bool blockAffiliateLinks,

            bool blockDisguisedTrackers)
        {
            BlockAdsAndTrackers = blockAdsAndTrackers;
            BlockAffiliateLinks = blockAffiliateLinks;
            BlockDisguisedTrackers = blockDisguisedTrackers;
        }
    }
}
