// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Twingate.Outputs
{

    [OutputType]
    public sealed class GetTwingateSecurityPoliciesSecurityPolicyResult
    {
        /// <summary>
        /// Return a matching Security Policy by its ID. The ID for the Security Policy can be obtained from the Admin API or the URL string in the Admin Console.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Return a Security Policy that exactly matches this name.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetTwingateSecurityPoliciesSecurityPolicyResult(
            string id,

            string name)
        {
            Id = id;
            Name = name;
        }
    }
}
