// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate.Outputs
{

    [OutputType]
    public sealed class GetTwingateDNSFilteringProfileDeniedDomainsResult
    {
        /// <summary>
        /// A set of denied domains.
        /// </summary>
        public readonly ImmutableArray<string> Domains;

        [OutputConstructor]
        private GetTwingateDNSFilteringProfileDeniedDomainsResult(ImmutableArray<string> domains)
        {
            Domains = domains;
        }
    }
}
