// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Twingate.Outputs
{

    [OutputType]
    public sealed class GetTwingateResourcesResourceProtocolResult
    {
        /// <summary>
        /// Whether to allow ICMP (ping) traffic
        /// </summary>
        public readonly bool AllowIcmp;
        public readonly ImmutableArray<Outputs.GetTwingateResourcesResourceProtocolTcpResult> Tcps;
        public readonly ImmutableArray<Outputs.GetTwingateResourcesResourceProtocolUdpResult> Udps;

        [OutputConstructor]
        private GetTwingateResourcesResourceProtocolResult(
            bool allowIcmp,

            ImmutableArray<Outputs.GetTwingateResourcesResourceProtocolTcpResult> tcps,

            ImmutableArray<Outputs.GetTwingateResourcesResourceProtocolUdpResult> udps)
        {
            AllowIcmp = allowIcmp;
            Tcps = tcps;
            Udps = udps;
        }
    }
}
