// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate.Outputs
{

    [OutputType]
    public sealed class TwingateGatewayConfigSshCa
    {
        /// <summary>
        /// Path to the SSH CA private key file. Can't be used together with vault.address.
        /// </summary>
        public readonly string? PrivateKeyFile;
        /// <summary>
        /// Vault SSH CA configuration.
        /// </summary>
        public readonly Outputs.TwingateGatewayConfigSshCaVault? Vault;

        [OutputConstructor]
        private TwingateGatewayConfigSshCa(
            string? privateKeyFile,

            Outputs.TwingateGatewayConfigSshCaVault? vault)
        {
            PrivateKeyFile = privateKeyFile;
            Vault = vault;
        }
    }
}
