// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate.Outputs
{

    [OutputType]
    public sealed class TwingateSSHResourceProtocols
    {
        /// <summary>
        /// Whether to allow ICMP (ping) traffic
        /// </summary>
        public readonly bool? AllowIcmp;
        public readonly Outputs.TwingateSSHResourceProtocolsTcp? Tcp;
        public readonly Outputs.TwingateSSHResourceProtocolsUdp? Udp;

        [OutputConstructor]
        private TwingateSSHResourceProtocols(
            bool? allowIcmp,

            Outputs.TwingateSSHResourceProtocolsTcp? tcp,

            Outputs.TwingateSSHResourceProtocolsUdp? udp)
        {
            AllowIcmp = allowIcmp;
            Tcp = tcp;
            Udp = udp;
        }
    }
}
