// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate.Outputs
{

    [OutputType]
    public sealed class TwingateGatewayConfigTls
    {
        /// <summary>
        /// Path to the TLS certificate file. Default: "/etc/gateway/tls.crt".
        /// </summary>
        public readonly string? CertificateFile;
        /// <summary>
        /// Path to the TLS private key file. Default: "/etc/gateway/tls.key".
        /// </summary>
        public readonly string? PrivateKeyFile;

        [OutputConstructor]
        private TwingateGatewayConfigTls(
            string? certificateFile,

            string? privateKeyFile)
        {
            CertificateFile = certificateFile;
            PrivateKeyFile = privateKeyFile;
        }
    }
}
