// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate.Outputs
{

    [OutputType]
    public sealed class TwingateWebAppResourceUpstream
    {
        /// <summary>
        /// The port number. Must be between 1 and 65535 inclusive.
        /// </summary>
        public readonly int Port;

        [OutputConstructor]
        private TwingateWebAppResourceUpstream(int port)
        {
            Port = port;
        }
    }
}
