// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate.Outputs
{

    [OutputType]
    public sealed class TwingateGatewayConfigSshCaVault
    {
        /// <summary>
        /// Vault server address. Can't be used together with ca.private*key*file.
        /// </summary>
        public readonly string? Address;
        /// <summary>
        /// Vault authentication configuration.
        /// </summary>
        public readonly Outputs.TwingateGatewayConfigSshCaVaultAuth? Auth;
        /// <summary>
        /// Path to the Vault CA bundle file. Default: "/etc/ssl/vault-ca.crt".
        /// </summary>
        public readonly string? CaBundleFile;
        /// <summary>
        /// Vault SSH secrets engine mount path. Default: "ssh".
        /// </summary>
        public readonly string? Mount;
        /// <summary>
        /// Vault role for signing certificates. Default: "gateway".
        /// </summary>
        public readonly string? Role;

        [OutputConstructor]
        private TwingateGatewayConfigSshCaVault(
            string? address,

            Outputs.TwingateGatewayConfigSshCaVaultAuth? auth,

            string? caBundleFile,

            string? mount,

            string? role)
        {
            Address = address;
            Auth = auth;
            CaBundleFile = caBundleFile;
            Mount = mount;
            Role = role;
        }
    }
}
