// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate.Inputs
{

    public sealed class GetTwingateDNSFilteringProfileAllowedDomainsArgs : global::Pulumi.InvokeArgs
    {
        [Input("domains", required: true)]
        private List<string>? _domains;

        /// <summary>
        /// A set of allowed domains.
        /// </summary>
        public List<string> Domains
        {
            get => _domains ?? (_domains = new List<string>());
            set => _domains = value;
        }

        public GetTwingateDNSFilteringProfileAllowedDomainsArgs()
        {
        }
        public static new GetTwingateDNSFilteringProfileAllowedDomainsArgs Empty => new GetTwingateDNSFilteringProfileAllowedDomainsArgs();
    }
}
