// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate.Inputs
{

    public sealed class GetTwingateDNSFilteringProfilePrivacyCategoriesInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to block ads and trackers.
        /// </summary>
        [Input("blockAdsAndTrackers", required: true)]
        public Input<bool> BlockAdsAndTrackers { get; set; } = null!;

        /// <summary>
        /// Whether to block affiliate links.
        /// </summary>
        [Input("blockAffiliateLinks", required: true)]
        public Input<bool> BlockAffiliateLinks { get; set; } = null!;

        /// <summary>
        /// Whether to block disguised third party trackers.
        /// </summary>
        [Input("blockDisguisedTrackers", required: true)]
        public Input<bool> BlockDisguisedTrackers { get; set; } = null!;

        public GetTwingateDNSFilteringProfilePrivacyCategoriesInputArgs()
        {
        }
        public static new GetTwingateDNSFilteringProfilePrivacyCategoriesInputArgs Empty => new GetTwingateDNSFilteringProfilePrivacyCategoriesInputArgs();
    }
}
