// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate.Inputs
{

    public sealed class TwingateGatewayConfigKubernetesResourceGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("address", required: true)]
        public Input<string> Address { get; set; } = null!;

        [Input("inCluster", required: true)]
        public Input<bool> InCluster { get; set; } = null!;

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public TwingateGatewayConfigKubernetesResourceGetArgs()
        {
        }
        public static new TwingateGatewayConfigKubernetesResourceGetArgs Empty => new TwingateGatewayConfigKubernetesResourceGetArgs();
    }
}
