// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate.Inputs
{

    public sealed class TwingateGatewayConfigSshCaGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Path to the SSH CA private key file. Can't be used together with vault.address.
        /// </summary>
        [Input("privateKeyFile")]
        public Input<string>? PrivateKeyFile { get; set; }

        /// <summary>
        /// Vault SSH CA configuration.
        /// </summary>
        [Input("vault")]
        public Input<Inputs.TwingateGatewayConfigSshCaVaultGetArgs>? Vault { get; set; }

        public TwingateGatewayConfigSshCaGetArgs()
        {
        }
        public static new TwingateGatewayConfigSshCaGetArgs Empty => new TwingateGatewayConfigSshCaGetArgs();
    }
}
