// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Twingate.Inputs
{

    public sealed class TwingateResourceProtocolsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to allow ICMP (ping) traffic
        /// </summary>
        [Input("allowIcmp")]
        public Input<bool>? AllowIcmp { get; set; }

        [Input("tcp")]
        public Input<Inputs.TwingateResourceProtocolsTcpArgs>? Tcp { get; set; }

        [Input("udp")]
        public Input<Inputs.TwingateResourceProtocolsUdpArgs>? Udp { get; set; }

        public TwingateResourceProtocolsArgs()
        {
        }
        public static new TwingateResourceProtocolsArgs Empty => new TwingateResourceProtocolsArgs();
    }
}
