// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Twingate.Inputs
{

    public sealed class TwingateResourceAccessGroupGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Group ID that will have permission to access the Resource.
        /// </summary>
        [Input("groupId")]
        public Input<string>? GroupId { get; set; }

        /// <summary>
        /// The ID of a `twingate.getTwingateSecurityPolicy` to use as the access policy for the group IDs in the access block.
        /// </summary>
        [Input("securityPolicyId")]
        public Input<string>? SecurityPolicyId { get; set; }

        public TwingateResourceAccessGroupGetArgs()
        {
        }
        public static new TwingateResourceAccessGroupGetArgs Empty => new TwingateResourceAccessGroupGetArgs();
    }
}
