// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate.Inputs
{

    public sealed class TwingateSSHResourceAccessGroupGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessPolicies")]
        private InputList<Inputs.TwingateSSHResourceAccessGroupAccessPolicyGetArgs>? _accessPolicies;

        /// <summary>
        /// Restrict access according to JIT access policy
        /// </summary>
        public InputList<Inputs.TwingateSSHResourceAccessGroupAccessPolicyGetArgs> AccessPolicies
        {
            get => _accessPolicies ?? (_accessPolicies = new InputList<Inputs.TwingateSSHResourceAccessGroupAccessPolicyGetArgs>());
            set => _accessPolicies = value;
        }

        /// <summary>
        /// Group ID that will have permission to access the Resource.
        /// </summary>
        [Input("groupId")]
        public Input<string>? GroupId { get; set; }

        /// <summary>
        /// The ID of a `twingate.getTwingateSecurityPolicy` to use as the access policy for the group IDs in the access block. Default is 'Null' which points to `Default Policy` on Admin console.
        /// </summary>
        [Input("securityPolicyId")]
        public Input<string>? SecurityPolicyId { get; set; }

        public TwingateSSHResourceAccessGroupGetArgs()
        {
        }
        public static new TwingateSSHResourceAccessGroupGetArgs Empty => new TwingateSSHResourceAccessGroupGetArgs();
    }
}
