// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Twingate.Twingate.Inputs
{

    public sealed class TwingateGatewayConfigSshGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// SSH CA configuration. Specify either vault.address or private*key*file, not both.
        /// </summary>
        [Input("ca")]
        public Input<Inputs.TwingateGatewayConfigSshCaGetArgs>? Ca { get; set; }

        /// <summary>
        /// SSH gateway settings. All fields are optional and fall back to built-in defaults.
        /// </summary>
        [Input("gateway")]
        public Input<Inputs.TwingateGatewayConfigSshGatewayGetArgs>? Gateway { get; set; }

        [Input("resources")]
        private InputList<Inputs.TwingateGatewayConfigSshResourceGetArgs>? _resources;

        /// <summary>
        /// List of SSH resources. Accepts full twingate*ssh*resource references.
        /// </summary>
        public InputList<Inputs.TwingateGatewayConfigSshResourceGetArgs> Resources
        {
            get => _resources ?? (_resources = new InputList<Inputs.TwingateGatewayConfigSshResourceGetArgs>());
            set => _resources = value;
        }

        public TwingateGatewayConfigSshGetArgs()
        {
        }
        public static new TwingateGatewayConfigSshGetArgs Empty => new TwingateGatewayConfigSshGetArgs();
    }
}
