name: Lint

on:
  workflow_call:
    inputs: {}
  pull_request:
    branches:
    - main
    - v*
    - feature*
    paths-ignore:
    - CHANGELOG.md

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v6
    - name: Install go
      uses: actions/setup-go@v6
      with:
        go-version-file: provider/go.mod
        cache: false
    - name: disarm go:embed directives to enable lint
      continue-on-error: true # this fails if there are no go:embed directives
      run: |
        git grep -l 'go:embed' -- provider | xargs sed -i 's/go:embed/ goembed/g'
    - name: prepare upstream
      continue-on-error: true
      run: make upstream
    - run: cd provider && go mod tidy
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9.2.0
      with:
        version: latest
        working-directory: provider
