// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Users in Twingate can be given access to Twingate Resources and may either be added manually or automatically synchronized with a 3rd party identity provider. For more information, see Twingate's [documentation](https://docs.twingate.com/docs/users).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as twingate from "@twingate/pulumi-twingate";
 *
 * const foo = twingate.getTwingateUser({
 *     id: "<your user's id>",
 * });
 * ```
 */
export function getTwingateUser(args: GetTwingateUserArgs, opts?: pulumi.InvokeOptions): Promise<GetTwingateUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("twingate:index/getTwingateUser:getTwingateUser", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getTwingateUser.
 */
export interface GetTwingateUserArgs {
    /**
     * The ID of the User. The ID for the User can be obtained from the Admin API or the URL string in the Admin Console.
     */
    id: string;
}

/**
 * A collection of values returned by getTwingateUser.
 */
export interface GetTwingateUserResult {
    /**
     * The email address of the User
     */
    readonly email: string;
    /**
     * The first name of the User
     */
    readonly firstName: string;
    /**
     * The ID of the User. The ID for the User can be obtained from the Admin API or the URL string in the Admin Console.
     */
    readonly id: string;
    /**
     * The last name of the User
     */
    readonly lastName: string;
    /**
     * Indicates the User's role. Either ADMIN, DEVOPS, SUPPORT, MEMBER or ACCESS_REVIEWER.
     */
    readonly role: string;
    /**
     * Indicates the User's type. Either MANUAL or SYNCED.
     */
    readonly type: string;
}
/**
 * Users in Twingate can be given access to Twingate Resources and may either be added manually or automatically synchronized with a 3rd party identity provider. For more information, see Twingate's [documentation](https://docs.twingate.com/docs/users).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as twingate from "@twingate/pulumi-twingate";
 *
 * const foo = twingate.getTwingateUser({
 *     id: "<your user's id>",
 * });
 * ```
 */
export function getTwingateUserOutput(args: GetTwingateUserOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTwingateUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("twingate:index/getTwingateUser:getTwingateUser", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getTwingateUser.
 */
export interface GetTwingateUserOutputArgs {
    /**
     * The ID of the User. The ID for the User can be obtained from the Admin API or the URL string in the Admin Console.
     */
    id: pulumi.Input<string>;
}
