// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Resources in Twingate represent servers on the private network that clients can connect to. Resources can be defined by IP, CIDR range, FQDN, or DNS zone. For more information, see the Twingate [documentation](https://docs.twingate.com/docs/resources-and-access-nodes).
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import twingate:index/twingateResource:TwingateResource resource UmVzb3VyY2U6MzQwNDQ3
 * ```
 */
export class TwingateResource extends pulumi.CustomResource {
    /**
     * Get an existing TwingateResource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TwingateResourceState, opts?: pulumi.CustomResourceOptions): TwingateResource {
        return new TwingateResource(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twingate:index/twingateResource:TwingateResource';

    /**
     * Returns true if the given object is an instance of TwingateResource.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TwingateResource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TwingateResource.__pulumiType;
    }

    /**
     * Restrict access to certain group
     */
    declare public readonly accessGroups: pulumi.Output<outputs.TwingateResourceAccessGroup[] | undefined>;
    /**
     * Restrict access according to JIT access policy
     */
    declare public readonly accessPolicies: pulumi.Output<outputs.TwingateResourceAccessPolicy[] | undefined>;
    /**
     * Restrict access to certain service account
     */
    declare public readonly accessServices: pulumi.Output<outputs.TwingateResourceAccessService[] | undefined>;
    /**
     * The Resource's IP/CIDR or FQDN/DNS zone
     */
    declare public readonly address: pulumi.Output<string>;
    /**
     * Set a DNS alias address for the Resource. Must be a DNS-valid name string.
     */
    declare public readonly alias: pulumi.Output<string | undefined>;
    /**
     * Set the resource as active or inactive. Default is `true`.
     */
    declare public readonly isActive: pulumi.Output<boolean>;
    /**
     * Determines whether assignments in the access block will override any existing assignments. Default is `true`. If set to `false`, assignments made outside of Terraform will be ignored.
     */
    declare public readonly isAuthoritative: pulumi.Output<boolean>;
    /**
     * Controls whether an "Open in Browser" shortcut will be shown for this Resource in the Twingate Client. Default is `false`.
     */
    declare public readonly isBrowserShortcutEnabled: pulumi.Output<boolean>;
    /**
     * Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `true`.
     */
    declare public readonly isVisible: pulumi.Output<boolean>;
    /**
     * The name of the Resource
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Restrict access to certain protocols and ports. By default or when this argument is not defined, there is no restriction, and all protocols and ports are allowed.
     */
    declare public readonly protocols: pulumi.Output<outputs.TwingateResourceProtocols>;
    /**
     * Remote Network ID where the Resource lives
     */
    declare public readonly remoteNetworkId: pulumi.Output<string>;
    /**
     * The ID of a `twingate.getTwingateSecurityPolicy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.
     */
    declare public readonly securityPolicyId: pulumi.Output<string>;
    /**
     * A map of key-value pair tags to set on this resource.
     */
    declare public readonly tags: pulumi.Output<{[key: string]: string}>;
    /**
     * A map of key-value pairs that represents all tags on this resource, including default tags from provider configuration.
     */
    declare public /*out*/ readonly tagsAll: pulumi.Output<{[key: string]: string}>;

    /**
     * Create a TwingateResource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TwingateResourceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TwingateResourceArgs | TwingateResourceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TwingateResourceState | undefined;
            resourceInputs["accessGroups"] = state?.accessGroups;
            resourceInputs["accessPolicies"] = state?.accessPolicies;
            resourceInputs["accessServices"] = state?.accessServices;
            resourceInputs["address"] = state?.address;
            resourceInputs["alias"] = state?.alias;
            resourceInputs["isActive"] = state?.isActive;
            resourceInputs["isAuthoritative"] = state?.isAuthoritative;
            resourceInputs["isBrowserShortcutEnabled"] = state?.isBrowserShortcutEnabled;
            resourceInputs["isVisible"] = state?.isVisible;
            resourceInputs["name"] = state?.name;
            resourceInputs["protocols"] = state?.protocols;
            resourceInputs["remoteNetworkId"] = state?.remoteNetworkId;
            resourceInputs["securityPolicyId"] = state?.securityPolicyId;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["tagsAll"] = state?.tagsAll;
        } else {
            const args = argsOrState as TwingateResourceArgs | undefined;
            if (args?.address === undefined && !opts.urn) {
                throw new Error("Missing required property 'address'");
            }
            if (args?.remoteNetworkId === undefined && !opts.urn) {
                throw new Error("Missing required property 'remoteNetworkId'");
            }
            resourceInputs["accessGroups"] = args?.accessGroups;
            resourceInputs["accessPolicies"] = args?.accessPolicies;
            resourceInputs["accessServices"] = args?.accessServices;
            resourceInputs["address"] = args?.address;
            resourceInputs["alias"] = args?.alias;
            resourceInputs["isActive"] = args?.isActive;
            resourceInputs["isAuthoritative"] = args?.isAuthoritative;
            resourceInputs["isBrowserShortcutEnabled"] = args?.isBrowserShortcutEnabled;
            resourceInputs["isVisible"] = args?.isVisible;
            resourceInputs["name"] = args?.name;
            resourceInputs["protocols"] = args?.protocols;
            resourceInputs["remoteNetworkId"] = args?.remoteNetworkId;
            resourceInputs["securityPolicyId"] = args?.securityPolicyId;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["tagsAll"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TwingateResource.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TwingateResource resources.
 */
export interface TwingateResourceState {
    /**
     * Restrict access to certain group
     */
    accessGroups?: pulumi.Input<pulumi.Input<inputs.TwingateResourceAccessGroup>[]>;
    /**
     * Restrict access according to JIT access policy
     */
    accessPolicies?: pulumi.Input<pulumi.Input<inputs.TwingateResourceAccessPolicy>[]>;
    /**
     * Restrict access to certain service account
     */
    accessServices?: pulumi.Input<pulumi.Input<inputs.TwingateResourceAccessService>[]>;
    /**
     * The Resource's IP/CIDR or FQDN/DNS zone
     */
    address?: pulumi.Input<string>;
    /**
     * Set a DNS alias address for the Resource. Must be a DNS-valid name string.
     */
    alias?: pulumi.Input<string>;
    /**
     * Set the resource as active or inactive. Default is `true`.
     */
    isActive?: pulumi.Input<boolean>;
    /**
     * Determines whether assignments in the access block will override any existing assignments. Default is `true`. If set to `false`, assignments made outside of Terraform will be ignored.
     */
    isAuthoritative?: pulumi.Input<boolean>;
    /**
     * Controls whether an "Open in Browser" shortcut will be shown for this Resource in the Twingate Client. Default is `false`.
     */
    isBrowserShortcutEnabled?: pulumi.Input<boolean>;
    /**
     * Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `true`.
     */
    isVisible?: pulumi.Input<boolean>;
    /**
     * The name of the Resource
     */
    name?: pulumi.Input<string>;
    /**
     * Restrict access to certain protocols and ports. By default or when this argument is not defined, there is no restriction, and all protocols and ports are allowed.
     */
    protocols?: pulumi.Input<inputs.TwingateResourceProtocols>;
    /**
     * Remote Network ID where the Resource lives
     */
    remoteNetworkId?: pulumi.Input<string>;
    /**
     * The ID of a `twingate.getTwingateSecurityPolicy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.
     */
    securityPolicyId?: pulumi.Input<string>;
    /**
     * A map of key-value pair tags to set on this resource.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * A map of key-value pairs that represents all tags on this resource, including default tags from provider configuration.
     */
    tagsAll?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

/**
 * The set of arguments for constructing a TwingateResource resource.
 */
export interface TwingateResourceArgs {
    /**
     * Restrict access to certain group
     */
    accessGroups?: pulumi.Input<pulumi.Input<inputs.TwingateResourceAccessGroup>[]>;
    /**
     * Restrict access according to JIT access policy
     */
    accessPolicies?: pulumi.Input<pulumi.Input<inputs.TwingateResourceAccessPolicy>[]>;
    /**
     * Restrict access to certain service account
     */
    accessServices?: pulumi.Input<pulumi.Input<inputs.TwingateResourceAccessService>[]>;
    /**
     * The Resource's IP/CIDR or FQDN/DNS zone
     */
    address: pulumi.Input<string>;
    /**
     * Set a DNS alias address for the Resource. Must be a DNS-valid name string.
     */
    alias?: pulumi.Input<string>;
    /**
     * Set the resource as active or inactive. Default is `true`.
     */
    isActive?: pulumi.Input<boolean>;
    /**
     * Determines whether assignments in the access block will override any existing assignments. Default is `true`. If set to `false`, assignments made outside of Terraform will be ignored.
     */
    isAuthoritative?: pulumi.Input<boolean>;
    /**
     * Controls whether an "Open in Browser" shortcut will be shown for this Resource in the Twingate Client. Default is `false`.
     */
    isBrowserShortcutEnabled?: pulumi.Input<boolean>;
    /**
     * Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `true`.
     */
    isVisible?: pulumi.Input<boolean>;
    /**
     * The name of the Resource
     */
    name?: pulumi.Input<string>;
    /**
     * Restrict access to certain protocols and ports. By default or when this argument is not defined, there is no restriction, and all protocols and ports are allowed.
     */
    protocols?: pulumi.Input<inputs.TwingateResourceProtocols>;
    /**
     * Remote Network ID where the Resource lives
     */
    remoteNetworkId: pulumi.Input<string>;
    /**
     * The ID of a `twingate.getTwingateSecurityPolicy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.
     */
    securityPolicyId?: pulumi.Input<string>;
    /**
     * A map of key-value pair tags to set on this resource.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
